# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Wed Mar 31 20:51:58 2021
# ------------------------------------------------

package:
  name: parso
  version: 0.8.2
source:
  fn: parso-0.8.2.tar.gz
  sha256: 12b83492c6239ce32ff5eed6d3639d6a536170723c6f3f1506869f1ace413398
  url: https://pypi.io/packages/source/p/parso/parso-0.8.2.tar.gz
build:
  noarch: python
  number: '0'
  script: /tmp/build/80754af9/parso_1617223946239/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . -vv
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - ca-certificates 2021.1.19 h06a4308_1
    - certifi 2020.12.5 py39h06a4308_0
    - ld_impl_linux-64 2.33.1 h53a641e_7
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1k h27cfd23_0
    - pip 21.0.1 py39h06a4308_0
    - python 3.9.2 hdb3f193_0
    - readline 8.1 h27cfd23_0
    - setuptools 52.0.0 py39h06a4308_0
    - sqlite 3.35.3 hdfb4753_0
    - tk 8.6.10 hbc83047_0
    - tzdata 2020f h52ac0ba_0
    - wheel 0.36.2 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - python >=3.6
test:
  imports:
    - parso
    - parso.pgen2
    - parso.python
about:
  description: 'Parso is a Python parser that supports error recovery and round-trip
    parsing for different Python versions (in multiple Python versions).

    Parso is also able to list multiple syntax errors in your python file.

    '
  dev_url: https://github.com/davidhalter/parso
  doc_url: https://parso.readthedocs.io/en/latest/
  home: https://github.com/davidhalter/parso
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python Parser
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - iron0012
    - synapticarbors
