# This file created by conda-build 3.21.5
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Mon Oct 18 09:28:36 2021
# ------------------------------------------------

package:
  name: pillow
  version: 8.4.0
source:
  sha256: b8e2f83c56e141920c39464b852de3719dfbfb6e3c99a2d8da0edf4fb33176ed
  url: https://pypi.io/packages/source/P/Pillow/Pillow-8.4.0.tar.gz
build:
  ignore_run_exports:
    - jpeg
    - tk
  number: '0'
  string: py37h5aabda8_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - gcc_impl_linux-64 7.5.0 h7105cf2_17
    - gcc_linux-64 7.5.0 h8f34230_30
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libgcc-devel_linux-64 7.5.0 hbbeae57_17
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.9.30 h06a4308_1
    - certifi 2021.10.8 py37h06a4308_0
    - freetype 2.10.4 h5ab3b9f_0
    - giflib 5.2.1 h7b6447c_0
    - jpeg 9d h7f8727e_0
    - lcms2 2.12 h3be6417_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libpng 1.6.37 hbc83047_0
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libtiff 4.1.0 h2733197_1
    - libwebp 1.2.0 h89dd481_0
    - lz4-c 1.9.3 h295c915_1
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1l h7f8727e_0
    - pip 21.2.2 py37h06a4308_0
    - python 3.7.11 h12debd9_0
    - readline 8.1 h27cfd23_0
    - setuptools 58.0.4 py37h06a4308_0
    - sqlite 3.36.0 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - wheel 0.37.0 pyhd3eb1b0_1
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
    - zstd 1.4.9 haebb681_0
  run:
    - freetype >=2.10.4,<3.0a0
    - jpeg
    - lcms2 >=2.12,<3.0a0
    - libgcc-ng >=7.5.0
    - libtiff >=4.1.0,<5.0a0
    - libwebp >=0.3.0
    - libwebp >=1.2.0,<1.3.0a0
    - olefile
    - python >=3.7,<3.8.0a0
    - tk
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - pip check
  imports:
    - PIL
    - PIL.Image
    - PIL.ImageCms
    - PIL._imaging
    - PIL._imagingft
    - PIL._imagingmath
    - PIL._imagingmorph
    - PIL._imagingtk
  requires:
    - aiohttp
    - fsspec
    - pip
    - requests
about:
  description: 'Pillow is the friendly PIL fork. PIL is the Python Imaging Library,

    adds image processing capabilities to your Python interpreter.

    '
  dev_url: https://github.com/python-pillow/Pillow
  doc_source_url: https://github.com/python-pillow/Pillow/blob/4.2.x/docs/index.rst
  doc_url: http://pillow.readthedocs.io/en/4.2.x/
  home: https://pillow.readthedocs.io
  license: LicenseRef-PIL
  license_family: Other
  license_file: LICENSE
  summary: Pillow is the friendly PIL fork by Alex Clark and Contributors
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - patricksnape
    - pelson
