# This file created by conda-build 3.21.5
# meta.yaml template originally from:
# /root/project/packaging/torchvision, last modified Fri Oct 15 15:30:48 2021
# ------------------------------------------------

package:
  name: torchvision
  version: 0.11.0
source:
  path: /root/project
build:
  features: null
  script: python setup.py install --single-version-externally-managed --record=record.txt
  script_env:
    - BUILD_VERSION
    - CUDA_HOME
    - FORCE_CUDA
    - TORCH_CUDA_ARCH_LIST
  string: py37_cu113
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2021.9.30 h06a4308_1
    - ffmpeg 4.2.2 h20bf706_0
    - freetype 2.10.4 h5ab3b9f_0
    - gmp 6.2.1 h2531618_2
    - gnutls 3.6.15 he1e5248_0
    - jpeg 9d h7f8727e_0
    - lame 3.100 h7b6447c_0
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libidn2 2.3.2 h7f8727e_0
    - libopus 1.3.1 h7b6447c_0
    - libpng 1.6.37 hbc83047_0
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libtasn1 4.16.0 h27cfd23_0
    - libunistring 0.9.10 h27cfd23_0
    - libvpx 1.7.0 h439df22_0
    - nettle 3.7.3 hbbd107a_1
    - openh264 2.1.0 hd408876_0
    - x264 1!157.20191217 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - blas 1.0 mkl
    - ca-certificates 2021.9.30 h06a4308_1
    - certifi 2021.10.8 py37h06a4308_0
    - cudatoolkit 11.3.1 h2bc3f7f_2
    - intel-openmp 2021.3.0 h06a4308_3350
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuv 1.40.0 h7b6447c_0
    - mkl 2021.3.0 h06a4308_520
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1l h7f8727e_0
    - pip 21.2.2 py37h06a4308_0
    - python 3.7.11 h12debd9_0
    - pytorch 1.10.0 py3.7_cuda11.3_cudnn8.2.0_0
    - pytorch-mutex 1.0 cuda
    - readline 8.1 h27cfd23_0
    - setuptools 58.0.4 py37h06a4308_0
    - sqlite 3.36.0 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - typing_extensions 3.10.0.2 pyh06a4308_0
    - wheel 0.37.0 pyhd3eb1b0_1
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - cudatoolkit >=11.3,<11.4
    - defaults::numpy >=1.11
    - ffmpeg >=4.2
    - jpeg
    - libpng
    - pillow >=5.3.0
    - python >=3.7,<3.8.0a0
    - pytorch==1.10.0
test:
  imports:
    - torchvision
    - torchvision.datasets
    - torchvision.transforms
  requires:
    - ca-certificates
    - jpeg
    - pytest
    - scipy
  source_files:
    - test
about:
  home: https://github.com/pytorch/vision
  license: BSD
  license_file: LICENSE
  summary: image and video datasets and models for torch deep learning
extra:
  copy_test_source_files: true
  final: true
