# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Sep  8 05:50:30 2021
# ------------------------------------------------

package:
  name: matplotlib-inline
  version: 0.1.3
source:
  sha256: a04bfba22e0d1395479f866853ec1ee28eea1485c1d69a6faf00dc3e24ff34ee
  url: https://pypi.io/packages/source/m/matplotlib-inline/matplotlib-inline-0.1.3.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/matplotlib-inline_1631080358261/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.5.30 ha878542_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 11.1.0 hc902ee8_8
    - libgomp 11.1.0 hc902ee8_8
    - libstdcxx-ng 11.1.0 h56837e0_8
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1l h7f98852_0
    - pip 21.2.4 pyhd8ed1ab_0
    - python 3.9.7 h49503c6_0_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 h46c0cb4_0
    - setuptools 58.0.2 py39hf3d152e_0
    - sqlite 3.36.0 h9cd32fc_0
    - tk 8.6.11 h27826a3_1
    - tzdata 2021a he74cb21_1
    - wheel 0.37.0 pyhd8ed1ab_1
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - python >=3.6
    - traitlets
test:
  commands:
    - pip check
  imports:
    - matplotlib_inline
    - matplotlib_inline.backend_inline
  requires:
    - ipython
    - matplotlib-base
    - pip
about:
  dev_url: https://github.com/ipython/matplotlib-inline
  home: https://github.com/ipython/matplotlib-inline
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Inline Matplotlib backend for Jupyter
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - Carreau
    - SylvainCorlay
    - martinRenou
