# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /feedstock/recipe, last modified Thu Mar 10 15:19:42 2022
# ------------------------------------------------

package:
  name: asttokens
  version: 2.0.5
source:
  fn: asttokens-2.0.5.tar.gz
  sha256: 9a54c114f02c7a9480d56550932546a3f1fe71d8a02f1bc7ccd0ee3ee35cf4d5
  url: https://pypi.io/packages/source/a/asttokens/asttokens-2.0.5.tar.gz
build:
  noarch: python
  number: '0'
  script: /opt/conda/conda-bld/asttokens_1646925590279/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . --no-deps -vv
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2022.2.1 h06a4308_0
    - certifi 2021.5.30 py310h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuuid 1.0.3 h7f8727e_2
    - ncurses 6.3 h7f8727e_2
    - openssl 1.1.1m h7f8727e_0
    - packaging 21.3 pyhd3eb1b0_0
    - pip 21.2.4 py310h06a4308_0
    - pyparsing 3.0.4 pyhd3eb1b0_0
    - python 3.10.0 h12debd9_5
    - readline 8.1.2 h7f8727e_1
    - setuptools 58.0.4 py310h06a4308_0
    - setuptools-scm 6.3.2 pyhd3eb1b0_0
    - setuptools_scm 6.3.2 hd3eb1b0_0
    - sqlite 3.37.2 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tomli 1.2.2 pyhd3eb1b0_0
    - tzdata 2021e hda174b7_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7f8727e_4
  run:
    - python >=3.5
    - six
test:
  imports:
    - asttokens
about:
  dev_url: https://github.com/gristlabs/asttokens
  home: https://github.com/gristlabs/asttokens
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The asttokens module annotates Python abstract syntax trees (ASTs) with
    the positions of tokens and text in the source code that generated them.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - dopplershift
