# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/mkl-service-2.3.0-python_3.6-on-linux_64, last modified Thu Dec  3 21:46:51 2020
# ------------------------------------------------

package:
    name: mkl-service
    version: 2.3.0
source:
    sha256: f0c61f44f29d1264a464c14791b042826f0f74da094c3355dcc295943c46fed5
    url: https://github.com/IntelPython/mkl-service/archive/v2.3.0.tar.gz
build:
    ignore_run_exports:
        - blas
        - mkl-service
    number: '0'
    string: py36he8ac12f_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 mkl
        - ca-certificates 2020.10.14 0
        - certifi 2020.11.8 py36h06a4308_0
        - cython 0.29.21 py36h2531618_0
        - intel-openmp 2019.4 243
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - mkl 2019.4 243
        - mkl-devel 2019.4 243
        - mkl-include 2019.4 243
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - python 3.6.12 hcff3b4d_2
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.2 py36h06a4308_2
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - mkl >=2019.4,<2020.0a0
        - python >=3.6,<3.7.0a0
        - six
test:
    commands:
        - nosetests -v mkl
    imports:
        - mkl
    requires:
        - nose
about:
    description: Intel(R) Math Kernel Library (Intel(R) MKL) support functions are
        subdivided into the following groups according to their purpose, such as Version
        Information Threading Control Timing Memory Management Conditional Numerical
        Reproducibility Control Miscellaneous
    home: http://github.com/IntelPython/mkl-service
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: Python hooks for Intel(R) Math Kernel Library runtime control settings.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - oleksandr-pavlyk
