# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/builder/ktietz/aggregate/python-3.6-feedstock/recipe, last modified Fri Jun  4 12:51:11 2021
# ------------------------------------------------

package:
  name: python
  version: 3.6.13
source:
  - patches:
      - 0001-Add-Anaconda-Distribution-version-logic.patch
      - 0002-Darwin-Omit-PYTHONFRAMEWORK-site-packages.patch
      - 0003-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
      - 0004-Win32-distutils-Also-look-for-executable.bat.patch
      - 0005-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - 0006-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
      - 0007-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
      - 0008-Support-cross-compiling-byte-code.patch
      - 0009-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
      - 0010-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
      - 0011-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - 0012-Win32-Do-not-download-externals.patch
      - 0013-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
      - 0014-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - 0015-Disable-new-dtags-in-unixccompiler.py.patch
      - 0016-Fix-cross-compilation-on-Debian-based-distros.patch
      - 0017-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - 0018-Unvendor-sqlite3.patch
    sha256: a47a43a53abb42286a2c11965343ff56711b9e64e8d11bf2c6701a4fb8ce1a0f
    url: https://www.python.org/ftp/python/3.6.13/Python-3.6.13.tar.xz
build:
  detect_binary_files_with_prefix: false
  ignore_run_exports:
    - bzip2
  no_link:
    - bin/python3.6
  number: '1'
  string: h12debd9_1
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - gcc_impl_linux-64 7.5.0 h7105cf2_17
    - gcc_linux-64 7.5.0 h8f34230_30
    - gxx_impl_linux-64 7.5.0 h0a5bf11_17
    - gxx_linux-64 7.5.0 hffc177d_30
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libgcc-devel_linux-64 7.5.0 hbbeae57_17
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-devel_linux-64 7.5.0 hf0c5c8d_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libx11-common-cos6-x86_64 1.6.4 4
    - libx11-cos6-x86_64 1.6.4 4
    - libx11-devel-cos6-x86_64 1.6.4 4
    - make 4.2.1 h1bed415_1
    - pkg-config 0.29.2 h1bed415_8
    - sysroot_linux-64 2.17 h57e8cba_10
    - xorg-x11-proto-devel-cos6-x86_64 7.7 4
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2021.5.25 h06a4308_1
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1k h27cfd23_0
    - readline 8.0 h7b6447c_0
    - sqlite 3.35.4 hdfb4753_0
    - tk 8.6.10 hbc83047_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7f8727e_4
  run:
    - ld_impl_linux-64
    - libffi >=3.3,<3.4.0a0
    - libgcc-ng >=7.5.0
    - libstdcxx-ng >=7.5.0
    - ncurses >=6.2,<7.0a0
    - openssl >=1.1.1k,<1.1.2a
    - readline >=8.0,<9.0a0
    - sqlite >=3.35.4,<4.0a0
    - tk >=8.6.10,<8.7.0a0
    - xz >=5.2.5,<6.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - python -V
    - python3 -V
    - 2to3 -h
    - pydoc -h
    - python3-config --help
    - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
about:
  description: 'Python is a widely used high-level, general-purpose, interpreted,
    dynamic

    programming language. Its design philosophy emphasizes code

    readability, and its syntax allows programmers to express concepts in

    fewer lines of code than would be possible in languages such as C++ or

    Java. The language provides constructs intended to enable clear programs

    on both a small and large scale.

    '
  dev_url: https://docs.python.org/devguide/
  doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
  doc_url: https://www.python.org/doc/versions/
  home: http://www.python.org/
  license: PSF
  license_file: LICENSE
  summary: General purpose programming language
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
