# This file created by conda-build 3.21.5
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/ipython-7.29.0-python_3.7-on-linux_64, last modified Wed Nov  3 12:52:20 2021
# ------------------------------------------------

package:
  name: ipython
  version: 7.29.0
source:
  sha256: 4f69d7423a5a1972f6347ff233e38bbf4df6a150ef20fbb00c635442ac3060aa
  url: https://pypi.io/packages/source/i/ipython/ipython-7.29.0.tar.gz
build:
  entry_points:
    - iptest = IPython.testing.iptestcontroller:main
    - iptest3 = IPython.testing.iptestcontroller:main
    - ipython = IPython:start_ipython
    - ipython3 = IPython:start_ipython
  number: '0'
  script: /tmp/build/80754af9/ipython_1635944172793/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . -vv --no-deps
  string: py37hb070fc8_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.10.26 h06a4308_2
    - certifi 2021.10.8 py37h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - ncurses 6.3 h7f8727e_0
    - openssl 1.1.1l h7f8727e_0
    - pip 21.2.2 py37h06a4308_0
    - python 3.7.11 h12debd9_0
    - readline 8.1 h27cfd23_0
    - setuptools 58.0.4 py37h06a4308_0
    - sqlite 3.36.0 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - wheel 0.37.0 pyhd3eb1b0_1
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - backcall
    - decorator
    - jedi >=0.16,<1.0
    - matplotlib-inline >=0.1.2
    - pexpect >4.3
    - pickleshare
    - prompt-toolkit >=2.0.0,!=3.0.0,!=3.0.1,<3.1.0
    - pygments
    - python >=3.7,<3.8.0a0
    - setuptools >=18.5
    - traitlets >=4.2
test:
  commands:
    - pip check
    - ipython -h
    - ipython3 -h
    - iptest -h
    - iptest3 -h
  imports:
    - IPython
    - IPython.core
    - IPython.core.magics
    - IPython.core.tests
    - IPython.extensions
    - IPython.extensions.tests
    - IPython.external
    - IPython.external.decorators
    - IPython.lib
    - IPython.lib.tests
    - IPython.sphinxext
    - IPython.terminal
    - IPython.terminal.pt_inputhooks
    - IPython.terminal.tests
    - IPython.testing
    - IPython.testing.plugin
    - IPython.testing.tests
    - IPython.utils
    - IPython.utils.tests
  requires:
    - curio
    - ipykernel
    - matplotlib-base
    - nbformat
    - nose >=0.10.1
    - numpy
    - pip
    - pygments
    - requests
    - testpath
    - trio
about:
  description: 'IPython provides a rich architecture for interactive computing with

    a powerful interactive shell, a kernel for Jupyter, high performance

    tools for parallel computing, and more.

    '
  dev_url: https://github.com/ipython/ipython
  doc_url: https://ipython.readthedocs.io
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'IPython: Productive Interactive Computing'
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - Carreau
    - blink1073
    - bollwyvl
    - ellisonbg
    - fperez
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
    - takluyver
