# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Thu Dec  1 19:55:44 2022
# ------------------------------------------------

package:
  name: typing_extensions
  version: 4.4.0
source:
  sha256: 1511434bb92bf8dd198c12b1cc812e800d4181cfcb867674e0f8279cc93087aa
  url: https://pypi.io/packages/source/t/typing_extensions/typing_extensions-4.4.0.tar.gz
build:
  number: '0'
  script: python -m pip install --no-deps --ignore-installed .
  string: py38h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - ca-certificates 2022.10.11 h06a4308_0
    - certifi 2022.9.24 py38h06a4308_0
    - flit-core 3.6.0 pyhd3eb1b0_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.2 h6a678d5_6
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - ncurses 6.3 h5eee18b_3
    - openssl 1.1.1s h7f8727e_0
    - pip 22.2.2 py38h06a4308_0
    - python 3.8.15 h7a1cb2a_2
    - readline 8.2 h5eee18b_0
    - setuptools 65.5.0 py38h06a4308_0
    - sqlite 3.40.0 h5082296_0
    - tk 8.6.12 h1ccaba5_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.6 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
  run:
    - flit-core >=3.6,<4
    - python >=3.8,<3.9.0a0
about:
  description: 'The typing module was added to the standard library in Python 3.5,
    but

    many new features have been added to the module since then.

    This means users of older Python versions who are unable to upgrade will not be

    able to take advantage of new types added to the typing module, such as

    typing.Protocol or typing.TypedDict.


    The typing_extensions module contains backports of these changes.

    Experimental types that will eventually be added to the ``typing``

    module are also included in typing_extensions.

    '
  dev_url: https://github.com/python/typing_extensions
  doc_url: https://github.com/python/typing_extensions/blob/main/README.md
  home: https://github.com/python/typing_extensions
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  summary: Backported and Experimental Type Hints for Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: b3de3926-e785-4059-b6e8-de422a69451c
  recipe-maintainers:
    - djsutherland
  remote_url: git@github.com:AnacondaRecipes/typing_extensions-feedstock.git
  sha: eed8e46a759bf3308cd0607b9a4dd522cf4e1757
