# This file created by conda-build 3.12.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Aug 13 06:29:19 2018
# ------------------------------------------------

package:
    name: backports
    version: '1.0'
build:
    noarch: python
    number: '2'
    script:
        - cd /home/conda/feedstock_root/build_artifacts/backports_1534141822256/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python2.7/site-packages
        - mkdir backports && cd backports
        - python -c "open('__init__.py', 'w').close()"
        - cd /home/conda/feedstock_root/build_artifacts/backports_1534141822256/work
        - python -c "import backports"
    string: py_2
requirements:
    build:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.4.16 0
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - python 2.7.15 h9fef7bc_0
        - readline 7.0 haf1bffa_1
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - zlib 1.2.11 h470a237_3
    run:
        - python
test:
    imports:
        - backports
about:
    home: http://github.com/conda-forge/backports-feedstock
    license: BSD 3-Clause
    license_family: BSD
    license_file: /home/conda/recipe_root/LICENSE.txt
    summary: A package to ensure the `backports` namespace is available.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
