# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/ktietz/src/aggregate/backcall-feedstock/recipe, last modified Wed Jan 27 12:54:45 2021
# ------------------------------------------------

package:
  name: backcall
  version: 0.2.0
source:
  fn: backcall-0.2.0.tar.gz
  sha256: 5cbdbf27be5e7cfadb448baf0aa95508f91f2bbc6c6437cd9cd06e2a4c215e1e
  url: https://pypi.io/packages/source/b/backcall/backcall-0.2.0.tar.gz
build:
  noarch: python
  number: '0'
  script: python -m pip install --no-deps --ignore-installed .
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2020.12.8 ha847dfd_0
    - certifi 2020.12.5 py39ha847dfd_0
    - flit-core 3.0.0 pyha847dfd_0
    - ld_impl_linux-s390x 2.33.1 h8daa219_19
    - libedit 3.1.20191231 h2a837d6_0
    - libffi 3.3 hd8db5ea_2
    - libgcc-ng 9.3.0 hcace7e0_18
    - libgomp 9.3.0 hcace7e0_18
    - libstdcxx-ng 9.3.0 hc891710_18
    - ncurses 6.2 h2a837d6_0
    - openssl 1.1.1i h2a837d6_0
    - pip 20.3.3 py39ha847dfd_0
    - python 3.9.1 h76587ff_2
    - pytoml 0.1.21 pyhd3eb1b0_0
    - readline 8.0 h2a837d6_0
    - setuptools 51.1.2 py39ha847dfd_4
    - sqlite 3.32.3 haa4ac92_0
    - tk 8.6.10 h2795051_1
    - tzdata 2020f h52ac0ba_0
    - wheel 0.36.2 pyhd3eb1b0_0
    - xz 5.2.5 h2a837d6_0
    - zlib 1.2.11 h2a837d6_4
  run:
    - python
test:
  imports:
    - backcall
about:
  description: 'Backcall provides a way of specifying the parameters that callback
    functions

    need to accept, and adapting callbacks that take fewer parameters, so you

    can add parameters to your callback API without breaking code that doesn''t

    know about them.

    '
  home: https://github.com/takluyver/backcall/
  license: BSD-3-Clause
  license_family: BSD
  summary: Specifications for callback functions passed in to an API
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - takluyver
