# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/harfbuzz-1.8.8-on-linux_64, last modified Mon Aug 27 18:39:05 2018
# ------------------------------------------------

package:
    name: harfbuzz
    version: 1.8.8
source:
    sha256: a8e5c86e4d99e1cc9865ec1b8e9b05b98e413c2a885cd11f8e9bb9502dd3e3a9
    url: https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-1.8.8.tar.bz2
build:
    number: '0'
    run_exports:
        - harfbuzz >=1.8.8,<2.0a0
    string: hffaf4a1_0
requirements:
    build:
        - autoconf 2.69 pl526hebd4dad_5
        - automake 1.15.1 pl526h7747ae0_0
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - ca-certificates 2018.03.07 0
        - cairo 1.14.12 h8948797_3
        - fontconfig 2.13.0 h9420a91_0
        - freetype 2.9.1 h8a8886c_0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - glib 2.56.1 h000015b_0
        - gobject-introspection 1.56.1 py37hbc4ca2d_2
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_3
        - icu 58.2 h9c2bf20_1
        - libedit 3.1.20170329 h6b74fdf_2
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libpng 1.6.34 hb9fc6fc_0
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - libtool 2.4.6 h544aabb_3
        - libuuid 1.0.3 h1bed415_2
        - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
        - libx11-cos6-x86_64 1.6.4 h64a1553_0
        - libx11-devel-cos6-x86_64 1.6.4 hb9851ce_0
        - libxau-cos6-x86_64 1.0.6 h4888106_0
        - libxau-devel-cos6-x86_64 1.0.6 hf5ff492_0
        - libxcb 1.13 h1bed415_1
        - libxext-cos6-x86_64 1.3.3 hc47956f_0
        - libxext-devel-cos6-x86_64 1.3.3 hf6a4bb0_0
        - libxml2 2.9.8 h26e45fe_1
        - libxrender-cos6-x86_64 0.9.10 h41db5cd_0
        - libxrender-devel-cos6-x86_64 0.9.10 ha8151bf_0
        - m4 1.4.18 h4e445db_0
        - make 4.2.1 h1bed415_1
        - ncurses 6.1 hf484d3e_0
        - openssl 1.0.2p h14c3975_0
        - pcre 8.42 h439df22_0
        - perl 5.26.2 h14c3975_0
        - pixman 0.34.0 hceecf20_3
        - pkg-config 0.29.2 h1bed415_8
        - python 3.7.0 hc3d631a_0
        - readline 7.0 ha6073c6_4
        - sqlite 3.24.0 h84994c4_0
        - tk 8.6.7 hc745277_3
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 ha838bed_2
    host:
        - cairo 1.14.12 h8948797_3
        - fontconfig 2.13.0 h9420a91_0
        - freetype 2.9.1 h8a8886c_0
        - glib 2.56.1 h000015b_0
        - graphite2 1.3.11 h16798f4_2
        - icu 58.2 h9c2bf20_1
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libpng 1.6.34 hb9fc6fc_0
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - libuuid 1.0.3 h1bed415_2
        - libxcb 1.13 h1bed415_1
        - libxml2 2.9.8 h26e45fe_1
        - pcre 8.42 h439df22_0
        - pixman 0.34.0 hceecf20_3
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 ha838bed_2
    run:
        - cairo >=1.14.12,<2.0a0
        - freetype >=2.9.1,<3.0a0
        - glib >=2.56.1,<2.57.0a0
        - graphite2 >=1.3.11,<2.0a0
        - icu >=58.2,<59.0a0
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - libxcb >=1.13,<2.0a0
test:
    commands:
        - test -f $PREFIX/lib/libharfbuzz-icu.so
        - test -f $PREFIX/lib/libharfbuzz.so
        - test -f $PREFIX/include/harfbuzz/hb-ft.h
        - hb-view --version
about:
    description: 'HarfBuzz is a text shaping library. New Harbuzz targets various
        font

        technologies while Old HarfBuzz targets only OpenType fonts.

        '
    dev_url: https://github.com/behdad/harfbuzz
    doc_url: https://www.freedesktop.org/wiki/Software/HarfBuzz/
    home: http://www.freedesktop.org/wiki/Software/HarfBuzz/
    license: MIT
    license_file: COPYING
    summary: An OpenType text shaping engine.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pkgw
