# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/icu-58.2-on-linux_canary, last modified Mon Apr 27 21:30:46 2020
# ------------------------------------------------

package:
    name: icu
    version: '58.2'
source:
    fn: icu4c-58_2-src.tgz
    patches:
        - CVE-2017-14952.patch
        - CVE-2017-15396.patch
        - CVE-2017-15422.patch
        - CVE-2017-7867_CVE-2017-7868.patch
        - CVE-2020-10531.patch
    sha256: 2b0a4410153a9b20de0e20c7d8b66049a72aef244b53683d0d7521371683da0c
    url:
        - http://download.icu-project.org/files/icu4c/58.2/icu4c-58_2-src.tgz
        - https://sourceforge.net/projects/icu/files/ICU4C/58.2/icu4c-58_2-src.tgz/download
build:
    number: '3'
    run_exports:
        - icu >=58.2,<59.0a0
    string: he6710b0_3
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - make 4.2.1 h1bed415_1
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
test:
    commands:
        - test -f $PREFIX/lib/libicudata.a
        - test -f $PREFIX/lib/libicudata.so.58.2
        - test -f $PREFIX/lib/libicui18n.a
        - test -f $PREFIX/lib/libicui18n.so.58.2
        - test -f $PREFIX/lib/libicuio.a
        - test -f $PREFIX/lib/libicuio.so.58.2
        - test -f $PREFIX/lib/libicutest.a
        - test -f $PREFIX/lib/libicutest.so.58.2
        - test -f $PREFIX/lib/libicutu.a
        - test -f $PREFIX/lib/libicutu.so.58.2
        - test -f $PREFIX/lib/libicuuc.a
        - test -f $PREFIX/lib/libicuuc.so.58.2
        - genbrk --help
        - gencfu --help
        - gencnval --help
        - gendict --help
        - icuinfo --help
        - icu-config --help
        - makeconv gb-18030-2000.ucm
        - conda inspect linkages -p $PREFIX icu
    files:
        - de.txt
        - gb-18030-2000.ucm
about:
    description: 'ICU is a mature, widely used set of C/C++ and Java libraries providing

        Unicode and Globalization support for software applications. ICU is

        widely portable and gives applications the same results on all platforms

        and between C/C++ and Java software.

        '
    dev_url: http://source.icu-project.org/repos/icu/
    doc_url: http://site.icu-project.org/design
    home: http://site.icu-project.org/
    license: MIT
    summary: International Components for Unicode.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - chenghlee
        - jakirkham
        - msarahan
        - ocefpaf
