# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pillow-9.0.1-python_3.8-on-linux_64, last modified Thu Mar  3 16:25:58 2022
# ------------------------------------------------

package:
  name: pillow
  version: 9.0.1
source:
  patches:
    - disable_detect.patch
  sha256: 6c8bc8238a7dfdaf7a75f5ec5a663f4173f8c367e5a39f87e720495e1eed75fa
  url: https://pypi.io/packages/source/p/pillow/Pillow-9.0.1.tar.gz
build:
  ignore_run_exports:
    - jpeg
    - tk
  number: '0'
  string: py38h22f2fdc_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - gcc_impl_linux-64 7.5.0 h7105cf2_17
    - gcc_linux-64 7.5.0 h8f34230_30
    - gxx_impl_linux-64 7.5.0 h0a5bf11_17
    - gxx_linux-64 7.5.0 hffc177d_30
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libgcc-devel_linux-64 7.5.0 hbbeae57_17
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-devel_linux-64 7.5.0 hf0c5c8d_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - patch 2.7.6 h7b6447c_1001
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2022.2.1 h06a4308_0
    - certifi 2021.10.8 py38h06a4308_2
    - freetype 2.10.4 h5ab3b9f_0
    - giflib 5.2.1 h7b6447c_0
    - jpeg 9d h7f8727e_0
    - lcms2 2.12 h3be6417_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libpng 1.6.37 hbc83047_0
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libtiff 4.1.0 h2733197_1
    - libwebp 1.2.0 h89dd481_0
    - lz4-c 1.9.3 h295c915_1
    - ncurses 6.3 h7f8727e_2
    - openssl 1.1.1m h7f8727e_0
    - pip 21.2.4 py38h06a4308_0
    - python 3.8.12 h12debd9_0
    - readline 8.1.2 h7f8727e_1
    - setuptools 58.0.4 py38h06a4308_0
    - sqlite 3.37.2 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7f8727e_4
    - zstd 1.4.9 haebb681_0
  run:
    - freetype >=2.10.4,<3.0a0
    - jpeg
    - lcms2 >=2.12,<3.0a0
    - libgcc-ng >=7.5.0
    - libstdcxx-ng >=7.5.0
    - libtiff >=4.1.0,<5.0a0
    - libwebp >=0.3.0
    - libwebp >=1.2.0,<1.3.0a0
    - python >=3.8,<3.9.0a0
    - tk
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - pip check
  imports:
    - PIL
    - PIL.Image
    - PIL.ImageCms
  requires:
    - pip
about:
  description: 'Pillow is the friendly PIL fork. PIL is the Python Imaging Library,

    adds image processing capabilities to your Python interpreter.

    '
  dev_url: https://github.com/python-pillow/Pillow
  doc_source_url: https://github.com/python-pillow/Pillow/blob/4.2.x/docs/index.rst
  doc_url: https://pillow.readthedocs.io/en/4.2.x/
  home: https://pillow.readthedocs.io
  license: LicenseRef-PIL
  license_family: Other
  license_file: LICENSE
  summary: Pillow is the friendly PIL fork by Alex Clark and Contributors
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - patricksnape
    - pelson
