# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libopus-1.3.1-on-linux_canary, last modified Fri Apr 17 13:09:54 2020
# ------------------------------------------------

package:
    name: libopus
    version: 1.3.1
source:
    git_rev: v1.3.1
    git_url: https://git.xiph.org/opus.git
build:
    number: '0'
    run_exports:
        - libopus >=1.3.1,<2.0a0
    string: h7b6447c_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - autoconf 2.69 pl526hebd4dad_5
        - automake 1.16.1 pl526_0
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - ca-certificates 2020.1.1 0
        - expat 2.2.6 he6710b0_0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - git 2.23.0 pl526hacde149_0
        - krb5 1.17.1 h173b8e3_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libcurl 7.69.1 h20c2e04_0
        - libedit 3.1.20181209 hc058e9b_0
        - libgcc-ng 9.1.0 hdf63c60_0
        - libssh2 1.9.0 h1ba5d50_1
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libtool 2.4.6 h7b6447c_5
        - m4 1.4.18 h4e445db_0
        - make 4.2.1 h1bed415_1
        - ncurses 6.2 he6710b0_0
        - openssl 1.1.1f h7b6447c_0
        - pcre 8.43 he6710b0_0
        - perl 5.26.2 h14c3975_0
        - tk 8.6.8 hbc83047_0
        - zlib 1.2.11 h7b6447c_3
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
    run:
        - libgcc-ng >=7.3.0
test:
    commands:
        - test -f ${PREFIX}/lib/libopus${SHLIB_EXT}
about:
    description: 'Opus is a totally open, royalty-free, highly versatile

        audio codec. Opus is unmatched for interactive speech

        and music transmission over the Internet, but is also

        intended for storage and streaming applications. It is

        standardized by the Internet Engineering Task Force

        (IETF) as RFC 6716 which incorporated technology from

        Skype''s SILK codec and Xiph.Org''s CELT codec.

        '
    dev_url: http://opus-codec.org/development/
    doc_url: http://opus-codec.org/docs/
    home: http://opus-codec.org/
    license: 3-clause BSD
    license_family: BSD
    summary: Opus Interactive Audio Codec
extra:
    copy_test_source_files: true
    final: true
