# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Feb  7 19:33:35 2022
# ------------------------------------------------

package:
  name: ipykernel
  version: 6.9.0
source:
  sha256: b556e292dc6fa223f24328b1c936b9c921fafcc2f420bb0d6cfdfc42eaa90225
  url: https://pypi.io/packages/source/i/ipykernel/ipykernel-6.9.0.tar.gz
build:
  number: '0'
  script:
    - /home/conda/feedstock_root/build_artifacts/ipykernel_1644262474683/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
      setup.py bdist_wheel
    - cd dist
    - /home/conda/feedstock_root/build_artifacts/ipykernel_1644262474683/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
      -m pip install ipykernel-6.9.0-py3-none-any.whl --no-deps -vv
    - /home/conda/feedstock_root/build_artifacts/ipykernel_1644262474683/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
      -m ipykernel install --sys-prefix
  script_env:
    - MIGRATING=False
  string: py37h6531663_0
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - backcall 0.2.0 pyh9f0ad1d_0
    - backports 1.0 py_2
    - backports.functools_lru_cache 1.6.4 pyhd8ed1ab_0
    - ca-certificates 2021.10.8 ha878542_0
    - debugpy 1.5.1 py37hcd2ae1e_0
    - decorator 5.1.1 pyhd8ed1ab_0
    - entrypoints 0.4 pyhd8ed1ab_0
    - ipython 7.31.1 py37h89c1867_0
    - jedi 0.18.1 py37h89c1867_0
    - jupyter_client 7.1.2 pyhd8ed1ab_0
    - jupyter_core 4.9.1 py37h89c1867_1
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 11.2.0 h1d223b6_12
    - libgomp 11.2.0 h1d223b6_12
    - libnsl 2.0.0 h7f98852_0
    - libsodium 1.0.18 h36c2ea0_1
    - libstdcxx-ng 11.2.0 he4da1e4_12
    - libzlib 1.2.11 h36c2ea0_1013
    - matplotlib-inline 0.1.3 pyhd8ed1ab_0
    - ncurses 6.3 h9c3ff4c_0
    - nest-asyncio 1.5.4 pyhd8ed1ab_0
    - openssl 3.0.0 h7f98852_2
    - parso 0.8.3 pyhd8ed1ab_0
    - pexpect 4.8.0 pyh9f0ad1d_2
    - pickleshare 0.7.5 py_1003
    - pip 22.0.3 pyhd8ed1ab_0
    - prompt-toolkit 3.0.26 pyha770c72_0
    - ptyprocess 0.7.0 pyhd3deb0d_0
    - pygments 2.11.2 pyhd8ed1ab_0
    - python 3.7.12 hf930737_100_cpython
    - python-dateutil 2.8.2 pyhd8ed1ab_0
    - python_abi 3.7 2_cp37m
    - pyzmq 22.3.0 py37h336d617_1
    - readline 8.1 h46c0cb4_0
    - setuptools 60.7.1 py37h89c1867_0
    - six 1.16.0 pyh6c4a22f_0
    - sqlite 3.37.0 h9cd32fc_0
    - tk 8.6.11 h27826a3_1
    - tornado 6.1 py37h5e8e339_2
    - traitlets 5.1.1 pyhd8ed1ab_0
    - wcwidth 0.2.5 pyh9f0ad1d_2
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.5 h516909a_1
    - zeromq 4.3.4 h9c3ff4c_1
    - zlib 1.2.11 h36c2ea0_1013
  run:
    - debugpy >=1.0.0,<2.0
    - ipython >=7.23.1
    - jupyter_client <8.0
    - matplotlib-inline >=0.1.0,<0.2.0
    - nest-asyncio
    - python >=3.7,<3.8.0a0
    - python_abi 3.7.* *_cp37m
    - tornado >=4.2,<7.0
    - traitlets >=5.1.0,<6.0
test:
  commands:
    - pip check
    - jupyter kernelspec list
  imports:
    - ipykernel
  requires:
    - curio
    - flaky
    - ipyparallel
    - matplotlib-base
    - numpy
    - pip
    - pytest !=5.3.4
    - pytest-cov
    - pytest-timeout
    - trio
about:
  description: 'A powerful interactive Python shell and a Jupyter kernel to work with

    Python code in Jupyter notebooks and other interactive frontends.

    '
  dev_url: https://github.com/ipython/ipykernel
  doc_source_url: https://github.com/ipython/ipykernel/blob/master/docs/index.rst
  doc_url: https://ipython.readthedocs.io
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: IPython Kernel for Jupyter
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - Carreau
    - blink1073
    - bollwyvl
    - davidbrochart
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
