# This file created by conda-build 3.17.7
# meta.yaml template originally from:
# /io/condarecipe10.0, last modified Tue Jan 22 23:56:58 2019
# ------------------------------------------------

package:
    name: cudatoolkit
    version: 10.0.130
source:
    path: /io/scripts
build:
    number: '0'
    script_env:
        - NVTOOLSEXT_INSTALL_PATH
    string: '0'
requirements:
    build:
        - asn1crypto 0.24.0 py37_0
        - ca-certificates 2018.12.5 0
        - certifi 2018.11.29 py37_0
        - cffi 1.11.5 py37he75722e_1
        - chardet 3.0.4 py37_1
        - conda 4.5.12 py37_0
        - conda-env 2.6.0 1
        - cryptography 2.4.2 py37h1ba5d50_0
        - idna 2.8 py37_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1a h7b6447c_0
        - pycosat 0.6.3 py37h14c3975_0
        - pycparser 2.19 py37_0
        - pyopenssl 18.0.0 py37_0
        - pysocks 1.6.8 py37_0
        - python 3.7.2 h0371630_0
        - pyyaml 3.13 py37h14c3975_0
        - readline 7.0 h7b6447c_5
        - requests 2.21.0 py37_0
        - ruamel_yaml 0.15.46 py37h14c3975_0
        - six 1.12.0 py37_0
        - sqlite 3.26.0 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - urllib3 1.24.1 py37_0
        - xz 5.2.4 h14c3975_4
        - yaml 0.1.7 had09818_2
        - zlib 1.2.11 h7b6447c_3
test:
    requires:
        - numba
extra:
    copy_test_source_files: true
    final: true
