# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /feedstock/recipe, last modified Fri May 20 11:56:41 2022
# ------------------------------------------------

package:
  name: libtiff
  version: 4.2.0
source:
  - folder: .
    patches:
      - patches/fix_TIFFReadRawStrip_man_page_typo.patch
      - patches/use_unix_io.patch
    sha256: eb0484e568ead8fa23b513e9b0041df7e327f4ee2d22db5a533929dfc19633cb
    url: https://download.osgeo.org/libtiff/tiff-4.2.0.tar.gz
build:
  ignore_run_exports: null
  missing_dso_whitelist:
    - /opt/X11/lib/libGL.1.dylib
    - /opt/X11/lib/libglut.3.dylib
  number: '1'
  run_exports:
    - libtiff >=4.2.0,<5.0a0
  string: h2818925_1
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - gcc_impl_linux-64 7.5.0 h7105cf2_17
    - gcc_linux-64 7.5.0 h8f34230_30
    - gxx_impl_linux-64 7.5.0 h0a5bf11_17
    - gxx_linux-64 7.5.0 hffc177d_30
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libgcc-devel_linux-64 7.5.0 hbbeae57_17
    - libgcc-ng 11.2.0 h1234567_0
    - libgomp 11.2.0 h1234567_0
    - libstdcxx-devel_linux-64 7.5.0 hf0c5c8d_17
    - libstdcxx-ng 11.2.0 h1234567_0
    - libtool 2.4.6 h295c915_1008
    - make 4.2.1 h1bed415_1
    - patch 2.7.6 h7b6447c_1001
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - jpeg 9e h7f8727e_0
    - libgcc-ng 11.2.0 h1234567_0
    - libgomp 11.2.0 h1234567_0
    - libstdcxx-ng 11.2.0 h1234567_0
    - libwebp-base 1.2.2 h7f8727e_0
    - lz4-c 1.9.3 h295c915_1
    - xz 5.2.5 h7f8727e_1
    - zlib 1.2.12 h7f8727e_2
    - zstd 1.5.2 ha4553b6_0
  run:
    - jpeg >=9e,<10a
    - libgcc-ng >=7.5.0
    - libstdcxx-ng >=7.5.0
    - libwebp-base
    - xz >=5.2.5,<6.0a0
    - zlib >=1.2.12,<1.3.0a0
    - zstd >=1.5.2,<1.6.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libtiff.a
    - test -f ${PREFIX}/lib/libtiffxx.a
    - test -f ${PREFIX}/lib/libtiff.so
    - test -f ${PREFIX}/lib/libtiffxx.so
about:
  description: 'This software provides support for the Tag Image File Format (TIFF),
    a

    widely used format for storing image data.

    '
  dev_url: https://gitlab.com/libtiff/libtiff
  doc_url: http://www.libtiff.org/document.html
  home: http://www.libtiff.org/
  license: HPND
  license_file: COPYRIGHT
  summary: Support for the Tag Image File Format (TIFF).
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 8be73bb1-1753-4bcf-ba52-a1be1182b2dc
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - stuarteberg
  remote_url: git@github.com:AnacondaRecipes/libtiff-feedstock.git
  sha: 87db9e325dcecf1c5dbc8ec0b1d771fef2bbbf22
