# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Mon Oct 10 10:17:50 2022
# ------------------------------------------------

package:
  name: libwebp
  version: 1.2.4
source:
  sha256: 7bf5a8a28cc69bcfa8cb214f2c3095703c6b73ac5fba4d5480c205331d9494df
  url: http://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.2.4.tar.gz
build:
  number: '0'
  run_exports:
    - libwebp-base >=1.2.4,<2.0a0
  string: h11a3e52_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - gnuconfig 2021.05.24 hd3eb1b0_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.38 h1181459_1
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - make 4.2.1 h1bed415_1
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - giflib 5.2.1 h7b6447c_0
    - jpeg 9e h7f8727e_0
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libpng 1.6.37 hbc83047_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libtiff 4.1.0 hecacb30_2
    - libwebp-base 1.2.4 h5eee18b_0
    - lz4-c 1.9.3 h295c915_1
    - xz 5.2.6 h5eee18b_0
    - zlib 1.2.12 h5eee18b_3
    - zstd 1.5.2 ha4553b6_0
  run:
    - giflib >=5.2.1,<5.3.0a0
    - jpeg >=9e,<10a
    - libgcc-ng >=11.2.0
    - libpng >=1.6.37,<1.7.0a0
    - libtiff >=4.1.0,<5.0a0
    - libwebp-base 1.2.4.*
test:
  commands:
    - test -f $PREFIX/bin/cwebp
    - test -f $PREFIX/bin/dwebp
    - test -f $PREFIX/bin/gif2webp
    - test -f $PREFIX/bin/img2webp
    - test -f $PREFIX/bin/webpinfo
    - test -f $PREFIX/bin/webpmux
    - test ! -f $PREFIX/lib/libwebdecoder.a
    - test ! -f $PREFIX/lib/libwebp.a
    - test ! -f $PREFIX/lib/libwebpdemux.a
    - test ! -f $PREFIX/lib/libwebpmux.a
    - dwebp examples/test.webp
  source_files:
    - examples/test.webp
about:
  description: 'WebP is a method of lossy and lossless compression that can be used
    on a large variety of photographic,

    translucent and graphical images found on the web. The degree of lossy compression
    is adjustable so a

    user can choose the trade-off between file size and image quality.

    '
  dev_url: https://chromium.googlesource.com/webm/libwebp
  doc_url: https://developers.google.com/speed/webp/docs/using
  home: https://developers.google.com/speed/webp/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: WebP image library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 0ce7febb-82bd-444e-abb1-3d6f8a806e7c
  recipe-maintainers:
    - carterbox
    - dschreij
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/libwebp-feedstock.git
  sha: fe34e5241ef0f195f4a908a571ff8fc78c1f4266
