# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/zstd-1.4.9-on-linux_64, last modified Wed Mar 31 21:53:54 2021
# ------------------------------------------------

package:
  name: zstd
  version: 1.4.9
source:
  fn: zstd-1.4.9.tar.gz
  sha256: acf714d98e3db7b876e5b540cbf6dee298f60eb3c0723104f6d3f065cd60d6a8
  url: https://github.com/facebook/zstd/archive/v1.4.9.tar.gz
build:
  number: '0'
  run_exports:
    - zstd >=1.4.9,<1.5.0a0
  string: haebb681_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - binutils_impl_linux-64 2.33.1 he6710b0_7
    - binutils_linux-64 2.33.1 h9595d00_15
    - ca-certificates 2021.1.19 h06a4308_1
    - cmake-binary 3.9.1 h2f8e2a0_1
    - gcc_impl_linux-64 7.3.0 habb00fd_1
    - gcc_linux-64 7.3.0 h553295d_15
    - gxx_impl_linux-64 7.3.0 hdf63c60_1
    - gxx_linux-64 7.3.0 h553295d_15
    - ld_impl_linux-64 2.33.1 h53a641e_7
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - make 4.2.1 h1bed415_1
    - ncurses 6.2 he6710b0_1
    - ninja 1.10.2 py39hff7bd54_0
    - openssl 1.1.1k h27cfd23_0
    - python 3.9.2 hdb3f193_0
    - readline 8.1 h27cfd23_0
    - sqlite 3.35.3 hdfb4753_0
    - tk 8.6.10 hbc83047_0
    - tzdata 2020f h52ac0ba_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  host:
    - _libgcc_mutex 0.1 main
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - lz4-c 1.9.3 h2531618_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - libgcc-ng >=7.3.0
    - libstdcxx-ng >=7.3.0
    - lz4-c >=1.9.3,<1.10.0a0
    - xz >=5.2.5,<6.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - zstd -be -i5
    - test -f ${PREFIX}/include/zstd.h
    - test -f ${PREFIX}/lib/libzstd.a
    - test -f ${PREFIX}/lib/libzstd.so
    - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
    - test -f ${PREFIX}/lib/pkgconfig/libzstd.pc
    - pkg-config --cflags libzstd
  requires:
    - pkg-config
about:
  description: 'Zstandard is a real-time compression algorithm, providing high compression

    ratios. It offers a very wide range of compression / speed trade-off, while

    being backed by a very fast decoder. It also offers a special mode for

    small data, called dictionary compression, and can create dictionaries from

    any sample set. Zstandard library is provided as open source software using

    a BSD license.

    '
  dev_url: https://github.com/facebook/zstd
  doc_url: https://facebook.github.io/zstd/zstd_manual.html
  home: http://www.zstd.net
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Zstandard - Fast real-time compression algorithm
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - chenghlee
    - msarahan
    - rmax
    - xhochy
