# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /feedstock/recipe, last modified Fri Apr 22 10:09:05 2022
# ------------------------------------------------

package:
  name: zstd
  version: 1.5.2
source:
  fn: zstd-1.5.2.tar.gz
  sha256: f7de13462f7a82c29ab865820149e778cbfe01087b3a55b5332707abf9db4a6e
  url: https://github.com/facebook/zstd/archive/v1.5.2.tar.gz
build:
  number: '0'
  run_exports:
    - zstd >=1.5.2,<1.6.0a0
  string: ha4553b6_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2022.3.29 h06a4308_1
    - cmake-no-system 3.16.5 h295c915_1
    - gcc_impl_linux-64 7.5.0 h7105cf2_17
    - gcc_linux-64 7.5.0 h8f34230_30
    - gxx_impl_linux-64 7.5.0 h0a5bf11_17
    - gxx_linux-64 7.5.0 hffc177d_30
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-devel_linux-64 7.5.0 hbbeae57_17
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-devel_linux-64 7.5.0 hf0c5c8d_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuuid 1.0.3 h7f8727e_2
    - make 4.2.1 h1bed415_1
    - ncurses 6.3 h7f8727e_2
    - ninja 1.10.2 py310hd09550d_3
    - openssl 1.1.1n h7f8727e_0
    - python 3.10.4 h12debd9_0
    - readline 8.1.2 h7f8727e_1
    - sqlite 3.38.2 hc218d9a_0
    - sysroot_linux-64 2.17 h57e8cba_10
    - tk 8.6.11 h1ccaba5_0
    - tzdata 2022a hda174b7_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.12 h7f8727e_1
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - lz4-c 1.9.3 h295c915_1
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.12 h7f8727e_1
  run:
    - libgcc-ng >=7.5.0
    - libstdcxx-ng >=7.5.0
    - lz4-c >=1.9.3,<1.10.0a0
    - xz >=5.2.5,<6.0a0
    - zlib >=1.2.12,<1.3.0a0
test:
  commands:
    - zstd -be -i5
    - test -f ${PREFIX}/include/zstd.h
    - test -f ${PREFIX}/lib/libzstd.a
    - test -f ${PREFIX}/lib/libzstd.so
    - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
    - test -f ${PREFIX}/lib/pkgconfig/libzstd.pc
    - pkg-config --cflags libzstd
  requires:
    - pkg-config
about:
  description: 'Zstandard is a real-time compression algorithm, providing high compression

    ratios. It offers a very wide range of compression / speed trade-off, while

    being backed by a very fast decoder. It also offers a special mode for

    small data, called dictionary compression, and can create dictionaries from

    any sample set. Zstandard library is provided as open source software using

    a BSD license.

    '
  dev_url: https://github.com/facebook/zstd
  doc_url: https://facebook.github.io/zstd/zstd_manual.html
  home: https://www.zstd.net
  license: BSD-3-Clause AND GPL-2.0-or-later
  license_family: BSD
  license_file: LICENSE
  summary: Zstandard - Fast real-time compression algorithm
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: e09c39ca-399d-4c21-9855-4174a92ce286
  recipe-maintainers:
    - chenghlee
    - msarahan
    - rmax
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/zstd-feedstock.git
  sha: 9cf374bd132100d99e8540772d630fd56708bf34
