# This file created by conda-build 3.21.8
# ------------------------------------------------

package:
  name: ninja-base
  version: 1.10.2
source:
  fn: v1.10.2.tar.gz
  sha256: ce35865411f0490368a8fc383f29071de6690cbadc27704734978221f25e2bed
  url: https://github.com/ninja-build/ninja/archive/v1.10.2.tar.gz
build:
  ignore_run_exports:
    - vc
  number: 5
  string: hd09550d_5
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - bzip2 1.0.8 h7b6447c_0
    - c-ares 1.18.1 h7f8727e_0
    - ca-certificates 2022.3.29 h06a4308_1
    - cmake 3.22.1 h1fce559_0
    - expat 2.4.4 h295c915_0
    - gcc_impl_linux-64 7.5.0 h7105cf2_17
    - gcc_linux-64 7.5.0 h8f34230_30
    - gxx_impl_linux-64 7.5.0 h0a5bf11_17
    - gxx_linux-64 7.5.0 hffc177d_30
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - krb5 1.19.2 hac12032_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libcurl 7.82.0 h0b77cf5_0
    - libedit 3.1.20210910 h7f8727e_0
    - libev 4.33 h7f8727e_1
    - libgcc-devel_linux-64 7.5.0 hbbeae57_17
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libnghttp2 1.46.0 hce63b2e_0
    - libssh2 1.10.0 h8f2d780_0
    - libstdcxx-devel_linux-64 7.5.0 hf0c5c8d_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuv 1.40.0 h7b6447c_0
    - lz4-c 1.9.3 h295c915_1
    - make 4.2.1 h1bed415_1
    - ncurses 6.3 h7f8727e_2
    - openssl 1.1.1n h7f8727e_0
    - rhash 1.4.1 h3c74f83_1
    - sysroot_linux-64 2.17 h57e8cba_10
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.12 h7f8727e_2
    - zstd 1.5.2 ha4553b6_0
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
  run:
    - libgcc-ng >=7.5.0
    - libstdcxx-ng >=7.5.0
test:
  commands:
    - ninja --version
about:
  dev_url: https://github.com/ninja-build/ninja
  doc_source_url: https://github.com/ninja-build/ninja/tree/master/doc
  doc_url: https://ninja-build.org/manual.html
  home: https://ninja-build.org/
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  summary: A small build system with a focus on speed
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 1ee34c1f-f50b-49c5-8d5d-f97f98a9d32b
  recipe-maintainers:
    - frol
  remote_url: git@github.com:AnacondaRecipes/ninja-feedstock.git
  sha: 02e0641538afcc8657eeeea966b1c0c672f6231d
