# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# /root/project/packaging/torchaudio, last modified Thu Aug  4 14:17:24 2022
# ------------------------------------------------

package:
  name: torchaudio
  version: 0.12.1
source:
  path: /root/project
build:
  script_env:
    - BUILD_VERSION
    - FFMPEG_ROOT
    - MACOSX_DEPLOYMENT_TARGET
    - TORCH_CUDA_ARCH_LIST
    - USE_CUDA
    - USE_FFMPEG
    - USE_OPENMP
  string: py38_cu102
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - blas 1.0 mkl
    - bzip2 1.0.8 h7b6447c_0
    - c-ares 1.18.1 h7f8727e_0
    - ca-certificates 2022.07.19 h06a4308_0
    - certifi 2022.6.15 py38h06a4308_0
    - cmake 3.22.1 h1fce559_0
    - cudatoolkit 10.2.89 hfd86e86_1
    - expat 2.4.4 h295c915_0
    - intel-openmp 2021.4.0 h06a4308_3561
    - krb5 1.19.2 hac12032_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libcurl 7.84.0 h91b91d3_0
    - libedit 3.1.20210910 h7f8727e_0
    - libev 4.33 h7f8727e_1
    - libffi 3.3 he6710b0_2
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libnghttp2 1.46.0 hce63b2e_0
    - libssh2 1.10.0 h8f2d780_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuv 1.40.0 h7b6447c_0
    - lz4-c 1.9.3 h295c915_1
    - mkl 2021.4.0 h06a4308_640
    - mkl-service 2.4.0 py38h7f8727e_0
    - mkl_fft 1.3.1 py38hd3c417c_0
    - mkl_random 1.2.2 py38h51133e4_0
    - ncurses 6.3 h5eee18b_3
    - ninja 1.10.2 h06a4308_5
    - ninja-base 1.10.2 hd09550d_5
    - numpy 1.23.1 py38h6c91a56_0
    - numpy-base 1.23.1 py38ha15fc14_0
    - openssl 1.1.1q h7f8727e_0
    - pip 22.1.2 py38h06a4308_0
    - pkg-config 0.29.2 h1bed415_8
    - python 3.8.13 h12debd9_0
    - pytorch 1.12.1 py3.8_cuda10.2_cudnn7.6.5_0
    - pytorch-mutex 1.0 cuda
    - readline 8.1.2 h7f8727e_1
    - rhash 1.4.1 h3c74f83_1
    - setuptools 61.2.0 py38h06a4308_0
    - six 1.16.0 pyhd3eb1b0_1
    - sqlite 3.39.0 h5082296_0
    - tk 8.6.12 h1ccaba5_0
    - typing_extensions 4.1.1 pyh06a4308_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h7f8727e_1
    - zlib 1.2.12 h7f8727e_2
    - zstd 1.5.2 ha4553b6_0
  run:
    - cudatoolkit >=10.2,<10.3
    - numpy>=1.11
    - python >=3.8,<3.9.0a0
    - pytorch-mutex 1.0 cuda
    - pytorch==1.12.1
  run_constrained:
    - cpuonly <0
test:
  imports:
    - torchaudio
    - torchaudio.datasets
    - torchaudio.io
    - torchaudio.kaldi_io
    - torchaudio.sox_effects
    - torchaudio.transforms
  requires:
    - pytest
    - pytorch-mutex 1.0 cuda
    - scipy
  source_files:
    - test
about:
  home: https://github.com/pytorch/audio
  license: BSD
  license_file: LICENSE
  summary: simple audio I/O for pytorch
extra:
  copy_test_source_files: true
  final: true
