# This file created by conda-build 3.21.5
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Thu Oct 28 12:04:14 2021
# ------------------------------------------------

package:
  name: freetype
  version: 2.11.0
source:
  sha256: a45c6b403413abd5706f3582f04c8339d26397c4304b78fa552f2215df64101f
  url: http://download.savannah.gnu.org/releases/freetype/freetype-2.11.0.tar.gz
build:
  number: '0'
  run_exports:
    - freetype >=2.11.0,<3.0a0
  string: h70c0345_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - gcc_impl_linux-64 7.5.0 h7105cf2_17
    - gcc_linux-64 7.5.0 h8f34230_30
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libgcc-devel_linux-64 7.5.0 hbbeae57_17
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - make 4.2.1 h1bed415_1
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libpng 1.6.37 hbc83047_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - libgcc-ng >=7.5.0
    - libpng >=1.6.37,<1.7.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - ${PREFIX}/bin/freetype-config --version
about:
  description: 'FreeType is designed to be small, efficient, highly customizable

    and portable while capable of producing high-quality output (glyph images)

    of most vector and bitmap font formats.

    '
  dev_url: https://gitlab.freedesktop.org/freetype/freetype
  doc_source_url: https://sourceforge.net/projects/freetype/?source=navbar
  doc_url: http://freetype.sourceforge.net/freetype2/documentation.html
  home: https://www.freetype.org/
  license: GPL-2.0-only and LicenseRef-FreeType
  license_file:
    - docs/FTL.TXT
    - docs/GPLv2.TXT
  summary: A Free, High-Quality, and Portable Font Engine
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ccordoba12
    - msarahan
    - ocefpaf
