# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libxml2-2.9.12-on-linux_64, last modified Wed Jun 23 19:47:37 2021
# ------------------------------------------------

package:
  name: libxml2
  version: 2.9.12
source:
  patches:
    - 0002-Make-and-install-a-pkg-config-file-on-Windows.patch
  sha256: c8d6681e38c56f172892c85ddc0852e1fd4b53b4209e7f4ebf17f7e2eae71d92
  url: http://xmlsoft.org/sources/libxml2-2.9.12.tar.gz
build:
  number: '0'
  run_exports:
    - libxml2 >=2.9.12,<2.10.0a0
  string: h03d6c58_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - autoconf 2.69 pl526hebd4dad_5
    - automake 1.16.2 pl526_0
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - gcc_impl_linux-64 9.3.0 h6df7d76_17
    - gcc_linux-64 9.3.0 h1ee779e_30
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libgcc-devel_linux-64 9.3.0 hb95220a_17
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libtool 2.4.6 h7b6447c_1005
    - m4 1.4.18 h4e445db_0
    - make 4.2.1 h1bed415_1
    - patch 2.7.6 h7b6447c_1001
    - perl 5.26.2 h14c3975_0
    - pkg-config 0.29.2 h1bed415_8
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - icu 58.2 he6710b0_3
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - icu >=58.2,<59.0a0
    - libgcc-ng >=9.3.0
    - xz >=5.2.5,<6.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - xmllint test.xml
    - conda inspect linkages -p $PREFIX libxml2
  files:
    - test.xml
about:
  description: 'Though libxml2 is written in C a variety of language

    bindings make it available in other environments.

    '
  dev_url: https://git.gnome.org/browse/libxml2/
  doc_source_url: https://github.com/GNOME/libxml2/blob/master/doc/index.html
  doc_url: http://xmlsoft.org/html/index.html
  home: http://xmlsoft.org/
  license: MIT
  license_family: MIT
  license_file: Copyright
  summary: The XML C parser and toolkit of Gnome
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - chenghlee
    - gillins
    - jakirkham
    - jschueller
    - mingwandroid
    - msarahan
    - ocefpaf
    - scopatz
