# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Feb 26 15:18:50 2022
# ------------------------------------------------

package:
  name: ipython
  version: 7.32.0
source:
  sha256: 468abefc45c15419e3c8e8c0a6a5c115b2127bafa34d7c641b1d443658793909
  url: https://pypi.io/packages/source/i/ipython/ipython-7.32.0.tar.gz
build:
  entry_points:
    - iptest = IPython.testing.iptestcontroller:main
    - iptest3 = IPython.testing.iptestcontroller:main
    - ipython = IPython:start_ipython
    - ipython3 = IPython:start_ipython
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/ipython_1645888813068/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . -vv --no-deps
  script_env:
    - IPYTHON_TESTING_TIMEOUT_SCALE=5
    - MIGRATING=False
  string: py37h89c1867_0
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.10.8 ha878542_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 11.2.0 h1d223b6_12
    - libgomp 11.2.0 h1d223b6_12
    - libnsl 2.0.0 h7f98852_0
    - libstdcxx-ng 11.2.0 he4da1e4_12
    - libzlib 1.2.11 h36c2ea0_1013
    - ncurses 6.3 h9c3ff4c_0
    - openssl 3.0.0 h7f98852_2
    - pip 22.0.3 pyhd8ed1ab_0
    - python 3.7.12 hf930737_100_cpython
    - python_abi 3.7 2_cp37m
    - readline 8.1 h46c0cb4_0
    - setuptools 60.9.3 py37h89c1867_0
    - sqlite 3.37.0 h9cd32fc_0
    - tk 8.6.12 h27826a3_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h36c2ea0_1013
  run:
    - backcall
    - decorator
    - jedi >=0.16
    - matplotlib-inline
    - pexpect >4.3
    - pickleshare
    - prompt-toolkit >=2.0.0,!=3.0.0,!=3.0.1,<3.1.0
    - pygments
    - python >=3.7,<3.8.0a0
    - python_abi 3.7.* *_cp37m
    - setuptools >=18.5
    - traitlets >=4.2
test:
  commands:
    - pip check
    - ipython -h
    - ipython3 -h
    - iptest -h
    - iptest3 -h
  imports:
    - IPython
    - IPython.core
    - IPython.core.magics
    - IPython.core.tests
    - IPython.extensions
    - IPython.extensions.tests
    - IPython.external
    - IPython.external.decorators
    - IPython.lib
    - IPython.lib.tests
    - IPython.sphinxext
    - IPython.terminal
    - IPython.terminal.pt_inputhooks
    - IPython.terminal.tests
    - IPython.testing
    - IPython.testing.plugin
    - IPython.testing.tests
    - IPython.utils
    - IPython.utils.tests
  requires:
    - curio
    - ipykernel
    - matplotlib-base
    - nbformat
    - nose >=0.10.1
    - numpy >=1.17
    - pip
    - pytest
    - requests
    - testpath
    - trio
about:
  description: 'IPython provides a rich architecture for interactive computing with

    a powerful interactive shell, a kernel for Jupyter, high performance

    tools for parallel computing, and more.

    '
  dev_url: https://github.com/ipython/ipython
  doc_url: https://ipython.readthedocs.io
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'IPython: Productive Interactive Computing'
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - Carreau
    - blink1073
    - bollwyvl
    - ellisonbg
    - fperez
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
    - takluyver
