# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/cudatoolkit-10.2.89-on-linux_64, last modified Wed Apr 29 14:03:13 2020
# ------------------------------------------------

package:
    name: cudatoolkit
    version: 10.2.89
source:
    path: /tmp/build/80754af9/rsync-recipes/cudatoolkit-10.2.89-on-linux_64
build:
    missing_dso_whitelist:
        - $RPATH/ld-linux-x86-64.so.2
        - $RPATH/libc.so.6
        - $RPATH/libdl.so.2
        - $RPATH/libm.so.6
        - $RPATH/libpthread.so.0
        - $RPATH/librt.so.1
    number: '1'
    script_env:
        - DEBUG_INSTALLER_PATH
        - NVTOOLSEXT_INSTALL_PATH
    string: hfd86e86_1
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - asn1crypto 1.3.0 py38_0
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py38_0
        - cffi 1.14.0 py38h2e261b9_0
        - chardet 3.0.4 py38_1003
        - cryptography 2.8 py38h1ba5d50_0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - idna 2.9 py_1
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_0
        - openssl 1.1.1g h7b6447c_0
        - pycparser 2.20 py_0
        - pyopenssl 19.1.0 py38_0
        - pysocks 1.7.1 py38_0
        - python 3.8.2 hcf32534_0
        - pyyaml 5.3.1 py38h7b6447c_0
        - readline 8.0 h7b6447c_0
        - requests 2.23.0 py38_0
        - six 1.14.0 py38_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - tqdm 4.45.0 py_0
        - urllib3 1.25.8 py38_0
        - xz 5.2.5 h7b6447c_0
        - yaml 0.1.7 had09818_2
        - zlib 1.2.11 h7b6447c_3
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
test:
    requires:
        - numba
        - python >=3.7
        - setuptools
extra:
    copy_test_source_files: true
    final: true
