# This file created by conda-build 3.0.15+50.g6024f3f
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/libiconv-feedstock/recipe, last modified Sun Sep 17 15:41:12 2017
# ------------------------------------------------

package:
    name: libiconv
    version: '1.15'
source:
    fn: libiconv-1.15.tar.gz
    patches:
        - glibc.patch
    sha256: ccf536620a45458d26ba83887a983b96827001e92a13847b45e4925cc8913178
    url: http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.15.tar.gz
build:
    number: '5'
    string: h63c8f33_5
requirements:
    build:
        - binutils_linux-64 2.28.1 he4fe6c7_1
        - gcc_linux-64 7.2.0 hc7b1ceb_1
    run:
        - libgcc-ng >=7.2.0
test:
    commands:
        - iconv --help
        - conda inspect linkages -p $PREFIX libiconv
about:
    description: 'This library provides an iconv() implementation, for use on systems
        which don''t have one,

        or whose implementation cannot convert from/to Unicode.

        '
    dev_url: http://git.savannah.gnu.org/cgit/libiconv.git/tree/
    doc_url: https://www.gnu.org/savannah-checkouts/gnu/libiconv/documentation/libiconv-1.15/iconv.1.html
    home: https://www.gnu.org/software/libiconv/
    license: GPL and LGPL
    summary: Provides iconv for systems which don't have one (or that cannot convert
        from/to Unicode.)
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jhamman
        - ocefpaf
