# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# /root/project/packaging/torchvision, last modified Wed Aug  3 13:35:19 2022
# ------------------------------------------------

package:
  name: torchvision
  version: 0.13.1
source:
  path: /root/project
build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  script_env:
    - BUILD_VERSION
    - CUDA_HOME
    - FORCE_CUDA
    - MACOSX_DEPLOYMENT_TARGET
    - TORCH_CUDA_ARCH_LIST
  string: py38_cu102
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2022.07.19 h06a4308_0
    - ffmpeg 4.2.2 h20bf706_0
    - freetype 2.11.0 h70c0345_0
    - gmp 6.2.1 h295c915_3
    - gnutls 3.6.15 he1e5248_0
    - jpeg 9e h7f8727e_0
    - lame 3.100 h7b6447c_0
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libidn2 2.3.2 h7f8727e_0
    - libopus 1.3.1 h7b6447c_0
    - libpng 1.6.37 hbc83047_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libtasn1 4.16.0 h27cfd23_0
    - libunistring 0.9.10 h27cfd23_0
    - libvpx 1.7.0 h439df22_0
    - nettle 3.7.3 hbbd107a_1
    - openh264 2.1.1 h4ff587b_0
    - x264 1!157.20191217 h7b6447c_0
    - zlib 1.2.12 h7f8727e_2
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - blas 1.0 mkl
    - ca-certificates 2022.07.19 h06a4308_0
    - certifi 2022.6.15 py38h06a4308_0
    - cudatoolkit 10.2.89 h8f6ccaa_8
    - intel-openmp 2022.0.1 h06a4308_3633
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.3 he6710b0_2
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - mkl 2022.0.1 h06a4308_117
    - ncurses 6.3 h5eee18b_3
    - openssl 1.1.1q h7f8727e_0
    - pip 22.1.2 py38h06a4308_0
    - python 3.8.13 h12debd9_0
    - pytorch 1.12.1 py3.8_cuda10.2_cudnn7.6.5_0
    - pytorch-mutex 1.0 cuda
    - readline 8.1.2 h7f8727e_1
    - setuptools 61.2.0 py38h06a4308_0
    - sqlite 3.39.0 h5082296_0
    - tk 8.6.12 h1ccaba5_0
    - typing_extensions 4.1.1 pyh06a4308_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h7f8727e_1
    - zlib 1.2.12 h7f8727e_2
  run:
    - cudatoolkit >=10.2,<10.3
    - defaults::numpy >=1.11
    - ffmpeg >=4.2
    - jpeg
    - libpng
    - pillow >=5.3.0, !=8.3.*
    - python >=3.8,<3.9.0a0
    - pytorch-mutex 1.0 cuda
    - pytorch==1.12.1
    - requests
  run_constrained:
    - cpuonly <0
test:
  imports:
    - torchvision
    - torchvision.datasets
    - torchvision.transforms
  requires:
    - ca-certificates
    - jpeg
    - pytest
    - scipy
  source_files:
    - test
about:
  home: https://github.com/pytorch/vision
  license: BSD
  license_file: LICENSE
  summary: image and video datasets and models for torch deep learning
extra:
  copy_test_source_files: true
  final: true
