# This file created by conda-build 3.21.5
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/jasper-2.0.14-on-linux_64, last modified Fri Oct  8 13:49:14 2021
# ------------------------------------------------

package:
  name: jasper
  version: 2.0.14
source:
  fn: jasper-2.0.14.tar.gz
  patches:
    - CVE-2018-9055-330751ce.patch
  sha256: 2a1f61e55afe8b4ce8115e1508c5d7cb314d56dfcc2dd323f90c072f88ccf57b
  url: https://ftp.osuosl.org/pub/blfs/conglomeration/jasper/jasper-2.0.14.tar.gz
build:
  ignore_run_exports:
    - jpeg
  missing_dso_whitelist:
    - $RPATH/libc.so.6
    - $RPATH/libm.so.6
  number: '2'
  run_exports:
    - jasper >=2.0.14,<3.0a0
  string: hd8c5072_2
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - bzip2 1.0.8 h7b6447c_0
    - c-ares 1.17.1 h27cfd23_0
    - ca-certificates 2021.7.5 h06a4308_1
    - cmake 3.19.6 h973ab73_0
    - expat 2.4.1 h2531618_2
    - gcc_impl_linux-64 7.5.0 h7105cf2_17
    - gcc_linux-64 7.5.0 h8f34230_30
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - krb5 1.19.2 hac12032_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libcurl 7.78.0 h0b77cf5_0
    - libdrm-cos6-x86_64 2.4.65 4
    - libedit 3.1.20210714 h7f8727e_0
    - libev 4.33 h7f8727e_1
    - libgcc-devel_linux-64 7.5.0 hbbeae57_17
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libnghttp2 1.41.0 hf8bcb03_2
    - libselinux-cos6-x86_64 2.0.94 4
    - libsepol-cos6-x86_64 2.0.41 4
    - libssh2 1.9.0 h1ba5d50_1
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuv 1.40.0 h7b6447c_0
    - libx11-common-cos6-x86_64 1.6.4 4
    - libx11-cos6-x86_64 1.6.4 4
    - libxau-cos6-x86_64 1.0.6 4
    - libxcb-cos6-x86_64 1.12 4
    - libxdamage-cos6-x86_64 1.1.3 4
    - libxext-cos6-x86_64 1.3.3 4
    - libxfixes-cos6-x86_64 5.0.3 4
    - libxi-cos6-x86_64 1.7.8 4
    - libxxf86vm-cos6-x86_64 1.1.3 4
    - lz4-c 1.9.3 h295c915_1
    - make 4.2.1 h1bed415_1
    - mesa-dri-drivers-cos6-x86_64 11.0.7 4
    - mesa-dri1-drivers-cos6-x86_64 7.11 4
    - mesa-libgl-cos6-x86_64 11.0.7 4
    - mesa-libgl-devel-cos6-x86_64 11.0.7 4
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1l h7f8727e_0
    - patch 2.7.6 h7b6447c_1001
    - rhash 1.4.1 h3c74f83_1
    - sysroot_linux-64 2.17 h57e8cba_10
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
    - zstd 1.4.9 haebb681_0
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - freeglut 3.0.0 hf484d3e_5
    - jpeg 9d h7f8727e_0
    - libgcc-ng 9.3.0 h5101ec6_17
    - libglu 9.0.0 hf484d3e_1
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
  run:
    - freeglut >=3.0.0,<4.0a0
    - jpeg
    - libgcc-ng >=7.5.0
    - libglu >=9.0.0,<10.0a0
test:
  commands:
    - jasper --version
about:
  dev_url: https://github.com/mdadams/jasper
  home: http://www.ece.uvic.ca/~frodo/jasper/
  license: JasPer 2.0
  license_file: LICENSE
  summary: A reference implementation of the codec specified in the JPEG-2000 Part-1
    standard.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jhamman
    - ocefpaf
