# This file created by conda-build 3.17.5
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Jan 20 09:17:53 2019
# ------------------------------------------------

package:
    name: parquet-cpp
    version: 1.5.1
build:
    noarch: generic
    number: '3'
    string: '3'
requirements:
    host:
        - arrow-cpp 0.11.1 py36h0e61e49_1004
        - blas 1.0 mkl
        - boost-cpp 1.68.0 h11c811c_1000
        - bzip2 1.0.6 h14c3975_1002
        - ca-certificates 2018.11.29 ha4d7672_0
        - icu 58.2 hf484d3e_1000
        - intel-openmp 2019.1 144
        - libffi 3.2.1 hf484d3e_1005
        - libgcc-ng 7.3.0 hdf63c60_0
        - libgfortran-ng 7.2.0 hdf63c60_3
        - libprotobuf 3.6.1 hdbcaa40_1000
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - mkl 2019.1 144
        - mkl_fft 1.0.10 py36h470a237_1
        - mkl_random 1.0.2 py36_0
        - ncurses 6.1 hf484d3e_1002
        - numpy 1.15.4 py36h7e9f1db_0
        - numpy-base 1.15.4 py36hde5b4d6_0
        - openssl 1.0.2p h14c3975_1002
        - python 3.6.7 hd21baee_1001
        - readline 7.0 hf8c457e_1001
        - sqlite 3.26.0 h67949de_1000
        - thrift-cpp 0.12.0 h23e226f_1000
        - tk 8.6.9 h84994c4_1000
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    run:
        - arrow-cpp >=0.11.0
        - arrow-cpp >=0.11.1,<0.12.0a0
test:
    commands:
        - test -f $PREFIX/include/parquet/api/reader.h
        - test -f $PREFIX/lib/libparquet.a
        - test -f $PREFIX/lib/libparquet.so
about:
    home: http://github.com/apache/arrow
    license: Apache 2.0
    summary: C++ libraries for the Apache Parquet file format
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - cpcloud
        - jreback
        - kou
        - kszucs
        - leifwalsh
        - pitrou
        - siddharthteotia
        - wesm
        - xhochy
