# This file created by conda-build 3.21.5
# meta.yaml template originally from:
# /builder/conda/pytorch-nightly, last modified Fri Oct 15 04:29:22 2021
# ------------------------------------------------

package:
  name: pytorch
  version: 1.10.0
source:
  path: /pytorch
build:
  detect_binary_files_with_prefix: false
  number: '0'
  script_env:
    - BUILD_SPLIT_CUDA
    - BUILD_TEST
    - CMAKE_ARGS
    - CMAKE_OSX_ARCHITECTURES
    - CONDA_CUDATOOLKIT_CONSTRAINT
    - CUDA_VERSION
    - CUDNN_VERSION
    - DEBUG
    - DEVELOPER_DIR
    - EXTRA_CAFFE2_CMAKE_FLAGS
    - USE_CUDA
    - USE_DISTRIBUTED
    - USE_FBGEMM
    - USE_GLOO_WITH_OPENSSL
    - USE_MKLDNN
    - USE_NNPACK
    - USE_QNNPACK
    - USE_WHOLE_CUDNN
  string: py3.7_cuda11.3_cudnn8.2.0_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - c-ares 1.17.1 h27cfd23_0
    - ca-certificates 2021.9.30 h06a4308_1
    - cmake 3.19.6 h973ab73_0
    - expat 2.4.1 h2531618_2
    - krb5 1.19.2 hac12032_0
    - libcurl 7.78.0 h0b77cf5_0
    - libedit 3.1.20210714 h7f8727e_0
    - libev 4.33 h7f8727e_1
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libnghttp2 1.41.0 hf8bcb03_2
    - libssh2 1.9.0 h1ba5d50_1
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuv 1.40.0 h7b6447c_0
    - lz4-c 1.9.3 h295c915_1
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1l h7f8727e_0
    - rhash 1.4.1 h3c74f83_1
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
    - zstd 1.4.9 haebb681_0
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - blas 1.0 mkl
    - ca-certificates 2021.9.30 h06a4308_1
    - certifi 2021.10.8 py37h06a4308_0
    - intel-openmp 2021.3.0 h06a4308_3350
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libllvm9 9.0.1 h4a3c616_1
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuv 1.40.0 h7b6447c_0
    - llvm-tools 9.0.1 h4a3c616_1
    - llvmdev 9.0.1 h4a3c616_1
    - magma-cuda113 2.5.2 1
    - mkl 2020.2 256
    - mkl-include 2021.3.0 h06a4308_520
    - mkl-service 2.3.0 py37he8ac12f_0
    - mkl_fft 1.3.0 py37h54f3939_0
    - mkl_random 1.1.1 py37h0573a6f_0
    - ncurses 6.2 he6710b0_1
    - ninja 1.10.2 hff7bd54_1
    - numpy 1.19.2 py37h54aff64_0
    - numpy-base 1.19.2 py37hfa32c7d_0
    - openssl 1.1.1l h7f8727e_0
    - pip 21.2.2 py37h06a4308_0
    - pkg-config 0.29.2 h1bed415_8
    - python 3.7.11 h12debd9_0
    - pyyaml 5.4.1 py37h27cfd23_1
    - readline 8.1 h27cfd23_0
    - setuptools 58.0.4 py37h06a4308_0
    - six 1.16.0 pyhd3eb1b0_0
    - sqlite 3.36.0 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - typing_extensions 3.10.0.2 pyh06a4308_0
    - wheel 0.37.0 pyhd3eb1b0_1
    - xz 5.2.5 h7b6447c_0
    - yaml 0.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - blas * mkl
    - cudatoolkit >=11.3,<11.4
    - libuv >=1.40.0,<2.0a0
    - mkl >=2018
    - python >=3.7,<3.8.0a0
    - pytorch-mutex 1.0 cuda
    - typing_extensions
  run_constrained:
    - cpuonly <0
test:
  commands:
    - OMP_NUM_THREADS=4 python ./test/run_test.py || true
  imports:
    - torch
  source_files:
    - test
about:
  home: http://pytorch.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: PyTorch is an optimized tensor library for deep learning using GPUs and
    CPUs.
extra:
  copy_test_source_files: true
  final: true
