# This file created by conda-build 3.21.5
# meta.yaml template originally from:
# /feedstock/recipe, last modified Mon Dec 20 15:32:52 2021
# ------------------------------------------------

package:
  name: openh264
  version: 2.1.1
source:
  fn: openh264-v2.1.1.tar.gz
  sha256: af173e90fce65f80722fa894e1af0d6b07572292e76de7b65273df4c0a8be678
  url: https://github.com/cisco/openh264/archive/v2.1.1.tar.gz
build:
  ignore_run_exports:
    - zlib
  number: '0'
  run_exports:
    - openh264 >=2.1.1,<2.2.0a0
  string: h4ff587b_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - gcc_impl_linux-64 7.5.0 h7105cf2_17
    - gcc_linux-64 7.5.0 h8f34230_30
    - gxx_impl_linux-64 7.5.0 h0a5bf11_17
    - gxx_linux-64 7.5.0 hffc177d_30
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libgcc-devel_linux-64 7.5.0 hbbeae57_17
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-devel_linux-64 7.5.0 hf0c5c8d_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - make 4.2.1 h1bed415_1
    - nasm 2.13.03 h7b6447c_1
    - pkg-config 0.29.2 h1bed415_8
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - zlib 1.2.11 h7f8727e_4
  run:
    - libgcc-ng >=7.5.0
    - libstdcxx-ng >=7.5.0
test:
  commands:
    - h264enc -h
    - test -f $PREFIX/bin/h264dec
    - test -f $PREFIX/lib/libopenh264.so
about:
  dev_url: https://github.com/cisco/openh264
  doc_url: https://github.com/cisco/openh264
  home: http://www.openh264.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OpenH264 is a codec library which supports H.264 encoding and decoding
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - 183amir
    - sdvillal
