# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /feedstock/recipe, last modified Mon Jan 31 14:11:41 2022
# ------------------------------------------------

package:
  name: decorator
  version: 5.1.1
source:
  sha256: 637996211036b6385ef91435e4fae22989472f9d571faba8927ba8253acbc330
  url: https://pypi.io/packages/source/d/decorator/decorator-5.1.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /opt/conda/conda-bld/decorator_1643638310831/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . --no-deps -vv
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.10.26 h06a4308_2
    - certifi 2021.10.8 py39h06a4308_2
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - ncurses 6.3 h7f8727e_2
    - openssl 1.1.1m h7f8727e_0
    - pip 21.2.4 py39h06a4308_0
    - python 3.9.7 h12debd9_1
    - readline 8.1.2 h7f8727e_1
    - setuptools 58.0.4 py39h06a4308_0
    - sqlite 3.37.0 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - tzdata 2021e hda174b7_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7f8727e_4
  run:
    - python >=3.5
test:
  commands:
    - pip check
  imports:
    - decorator
  requires:
    - pip
    - python <3.10
about:
  description: 'Preserve the signature of decorated functions in a consistent way

    across Python releases.

    '
  dev_url: https://github.com/micheles/decorator
  doc_source_url: https://github.com/micheles/decorator/tree/5.1.1/docs
  doc_url: https://github.com/micheles/decorator/blob/master/docs/documentation.md
  home: https://github.com/micheles/decorator
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Better living through Python with decorators.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
