# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /root/project/packaging/torchvision, last modified Tue Apr 21 02:00:33 2020
# ------------------------------------------------

package:
    name: torchvision
    version: 0.6.0
source:
    path: /root/project
build:
    script: python setup.py install --single-version-externally-managed --record=record.txt
    script_env:
        - CUDA_HOME
        - FORCE_CUDA
        - NVCC_FLAGS
    string: py37_cu102
requirements:
    host:
        - sqlite 3.31.1 h7b6447c_0
        - six 1.14.0 py37_0
        - blas 1.0 mkl
        - mkl_random 1.1.0 py37hd6b4f25_0
        - cudatoolkit 10.2.89 hfd86e86_0
        - xz 5.2.5 h7b6447c_0
        - pip 20.0.2 py37_1
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - pytorch 1.5.0 py3.7_cuda10.2.89_cudnn7.6.5_0
        - mkl 2020.0 166
        - mkl_fft 1.0.15 py37ha843d7b_0
        - python 3.7.7 hcf32534_0_cpython
        - tk 8.6.8 hbc83047_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - certifi 2020.4.5.1 py37_0
        - numpy 1.18.1 py37h4f9e942_0
        - mkl-service 2.3.0 py37he904b0f_0
        - wheel 0.34.2 py37_0
        - _libgcc_mutex 0.1 main
        - ncurses 6.2 he6710b0_0
        - numpy-base 1.18.1 py37hde5b4d6_1
        - ca-certificates 2020.1.1 0
        - libgcc-ng 9.1.0 hdf63c60_0
        - libffi 3.2.1 hd88cf55_4
        - ninja 1.9.0 py37hfd86e86_0
        - readline 8.0 h7b6447c_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - zlib 1.2.11 h7b6447c_3
        - openssl 1.1.1f h7b6447c_0
        - intel-openmp 2020.0 166
        - setuptools 46.1.3 py37_0
    run:
        - cudatoolkit >=10.2,<10.3
        - numpy >=1.11
        - pillow >=4.1.1
        - python >=3.7,<3.8.0a0
        - pytorch==1.5.0
test:
    commands: pytest . --verbose --junitxml=/root/project/build_results/results.xml
    imports:
        - torchvision
        - torchvision.datasets
        - torchvision.transforms
    requires:
        - av
        - ca-certificates
        - mock
        - pytest
        - scipy
    source_files:
        - test
about:
    home: https://github.com/pytorch/vision
    license: BSD
    license_file: LICENSE
    summary: image and video datasets and models for torch deep learning
extra:
    copy_test_source_files: true
    final: true
