# This file created by conda-build 3.7.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/freeglut-3.0.0-on-nwani-linux-64, last modified Sun Mar 11 11:22:34 2018
# ------------------------------------------------

package:
    name: freeglut
    version: 3.0.0
source:
    fn: freeglut-3.0.0.tar.bz2
    md5: 90c3ca4dd9d51cf32276bc5344ec9754
    url: http://sourceforge.net/projects/freeglut/files/freeglut/3.0.0/freeglut-3.0.0.tar.gz
build:
    number: '5'
    string: hf484d3e_5
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 25
        - bzip2 1.0.6 h9a117a8_4
        - ca-certificates 2017.08.26 h1d4fec5_0
        - cmake 3.9.4 h142f0e9_0
        - curl 7.58.0 h84994c4_0
        - expat 2.2.5 he0dffb1_0
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 25
        - gxx_impl_linux-64 7.2.0 hdf63c60_3
        - gxx_linux-64 7.2.0 25
        - libcurl 7.58.0 h1ad7b7a_0
        - libdrm-cos6-x86_64 2.4.65 hd39d64f_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - libssh2 1.8.0 h9cfc8f7_4
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - libuv 1.19.2 h14c3975_0
        - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
        - libx11-cos6-x86_64 1.6.4 h64a1553_0
        - libx11-devel-cos6-x86_64 1.6.4 hb9851ce_0
        - libxau-cos6-x86_64 1.0.6 h4888106_0
        - libxau-devel-cos6-x86_64 1.0.6 hf5ff492_0
        - libxcb-cos6-x86_64 1.12 h6fd0490_0
        - libxext-cos6-x86_64 1.3.3 hc47956f_0
        - libxext-devel-cos6-x86_64 1.3.3 hf6a4bb0_0
        - libxfixes-cos6-x86_64 5.0.3 h3a64028_0
        - libxfixes-devel-cos6-x86_64 5.0.3 0
        - libxi-cos6-x86_64 1.7.8 h5354da0_0
        - libxi-devel-cos6-x86_64 1.7.8 hda042b6_0
        - mesa-libgl-cos6-x86_64 11.0.7 h045e36e_0
        - mesa-libgl-devel-cos6-x86_64 11.0.7 h5a2c0ac_0
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2n hb7f436b_0
        - rhash 1.3.5 hbf7ad62_1
        - xorg-x11-proto-devel-cos6-x86_64 7.7 h8d4a98b_0
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
        - libglu 9.0.0 h0c0bdc1_1
        - libstdcxx-ng 7.2.0 hdf63c60_3
    run:
        - libgcc-ng >=7.2.0
        - libstdcxx-ng >=7.2.0
test:
    commands:
        - test -d "${PREFIX}/include/GL"
        - test -f "${PREFIX}/lib/libglut.a"
        - test -f "${PREFIX}/lib/libglut.so"
        - ldd "${PREFIX}/lib/libglut.so"
about:
    home: http://freeglut.sourceforge.net/
    license: MIT
    license_family: MIT
    license_file: COPYING
    summary: A GUI based on OpenGL.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - shadowwalkersb
