# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/fontconfig-2.13.1-on-linux_64, last modified Thu Feb  4 14:48:34 2021
# ------------------------------------------------

package:
  name: fontconfig
  version: 2.13.1
source:
  patches:
    - fcf.patch
  sha256: f655dd2a986d7aa97e052261b36aa67b0a64989496361eca8d604e6414006741
  url: http://www.freedesktop.org/software/fontconfig/release/fontconfig-2.13.1.tar.bz2
build:
  binary_has_prefix_files:
    - lib/libfontconfig.so.1.*
  number: '0'
  run_exports:
    - fontconfig >=2.13.1,<3.0a0
  string: h6c09931_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - autoconf 2.69 pl526hebd4dad_5
    - automake 1.16.2 pl526_0
    - binutils_impl_linux-64 2.33.1 he6710b0_7
    - binutils_linux-64 2.33.1 h9595d00_15
    - gcc_impl_linux-64 7.3.0 habb00fd_1
    - gcc_linux-64 7.3.0 h553295d_15
    - gettext 0.19.8.1 hd7bead4_3
    - gperf 3.1 hb29a3a9_0
    - ld_impl_linux-64 2.33.1 h53a641e_7
    - libffi 3.2.1 hf484d3e_1007
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - libtool 2.4.6 h7b6447c_1005
    - m4 1.4.18 h4e445db_0
    - make 4.2.1 h1bed415_1
    - perl 5.26.2 h14c3975_0
    - pkg-config 0.29.2 h1bed415_8
  host:
    - _libgcc_mutex 0.1 main
    - freetype 2.10.4 h5ab3b9f_0
    - icu 58.2 he6710b0_3
    - libgcc-ng 9.1.0 hdf63c60_0
    - libpng 1.6.37 hbc83047_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - libuuid 1.0.3 h1bed415_2
    - libxml2 2.9.10 hb55368b_3
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - freetype >=2.10.4,<3.0a0
    - libgcc-ng >=7.3.0
    - libuuid >=1.0.3,<2.0a0
    - libxml2 >=2.9.10,<2.10.0a0
test:
  commands:
    - fc-cache --help
    - fc-cat --help
    - fc-list --help
    - fc-match --help
    - fc-pattern --help
    - fc-query --help
    - fc-scan --help
    - fc-validate --help
    - test -f "${PREFIX}/lib/libfontconfig.a"
    - test -f "${PREFIX}/lib/libfontconfig.so"
about:
  description: 'Fontconfig is a library designed to provide system-wide font configuration,

    customization and application access.

    '
  dev_url: https://cgit.freedesktop.org/fontconfig/
  doc_url: https://www.freedesktop.org/software/fontconfig/fontconfig-user.html
  home: http://www.freedesktop.org/wiki/Software/fontconfig/
  license: MIT
  license_file: COPYING
  summary: A library for configuring and customizing font access.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pkgw
