# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jul 19 08:04:33 2021
# ------------------------------------------------

package:
  name: numpy
  version: 1.19.5
source:
  patches:
    - cblas.diff
  sha256: d1654047d75fb9d55cc3d46f312d5247eec5f4999039874d2f571bb8021d8f0b
  url: https://github.com/numpy/numpy/releases/download/v1.19.5/numpy-1.19.5.tar.gz
build:
  entry_points: null
  number: '2'
  string: py37h038b26d_2
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - binutils_impl_linux-64 2.36.1 h193b22a_1
    - binutils_linux-64 2.36 hf3e587d_32
    - gcc_impl_linux-64 9.3.0 h70c0ae5_19
    - gcc_linux-64 9.3.0 hf25ea35_32
    - kernel-headers_linux-64 2.6.32 he073ed8_14
    - ld_impl_linux-64 2.36.1 hea4e1c9_1
    - libgcc-devel_linux-64 9.3.0 h7864c58_19
    - libgcc-ng 9.3.0 h2828fa1_19
    - libgomp 9.3.0 h2828fa1_19
    - libstdcxx-ng 9.3.0 h6de172a_19
    - sysroot_linux-64 2.12 he073ed8_14
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.5.30 ha878542_0
    - certifi 2021.5.30 py37h89c1867_0
    - cython 0.29.24 py37hcd2ae1e_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_1
    - libblas 3.8.0 11_h86c2bf4_netlib
    - libcblas 3.8.0 11_h86c2bf4_netlib
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h2828fa1_19
    - libgfortran-ng 9.3.0 hff62375_19
    - libgfortran5 9.3.0 hff62375_19
    - libgomp 9.3.0 h2828fa1_19
    - liblapack 3.8.0 11_h86c2bf4_netlib
    - libstdcxx-ng 9.3.0 h6de172a_19
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - pip 21.1.3 pyhd8ed1ab_0
    - python 3.7.10 hffdb5ce_100_cpython
    - python_abi 3.7 2_cp37m
    - readline 8.1 h46c0cb4_0
    - setuptools 49.6.0 py37h89c1867_3
    - sqlite 3.36.0 h9cd32fc_0
    - tk 8.6.10 h21135ba_1
    - wheel 0.36.2 pyhd3deb0d_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - libblas >=3.8.0,<4.0a0
    - libcblas >=3.8.0,<4.0a0
    - libgcc-ng >=9.3.0
    - liblapack >=3.8.0,<4.0a0
    - python >=3.7,<3.8.0a0
    - python_abi 3.7.* *_cp37m
test:
  commands:
    - f2py -h
    - python -c "import numpy as np; np.test(verbose=3, durations=50, extra_argv=['-k',
      'not (_not_a_real_test or test_sincos_float32)', ''])"
  imports:
    - numpy
    - numpy.core._multiarray_tests
    - numpy.core._operand_flag_tests
    - numpy.core._rational_tests
    - numpy.core._struct_ufunc_tests
    - numpy.core._umath_tests
    - numpy.core.multiarray
    - numpy.core.numeric
    - numpy.core.umath
    - numpy.linalg.lapack_lite
    - numpy.random.mtrand
  requires:
    - hypothesis
    - pytest
    - setuptools
about:
  dev_url: https://github.com/numpy/numpy
  doc_url: https://docs.scipy.org/doc/numpy/reference/
  home: http://numpy.scipy.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Array processing for numbers, strings, records, and objects.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - isuruf
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
    - rgommers
    - xhochy
