# This file created by conda-build 3.5.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libvpx-1.7.0-on-nwani-linux-64, last modified Tue Feb 27 18:57:46 2018
# ------------------------------------------------

package:
    name: libvpx
    version: 1.7.0
source:
    git_rev: v1.7.0
    git_url: https://chromium.googlesource.com/webm/libvpx
    patches:
        - 0001-Linux-Include-unistd-h-for-off_t.patch
build:
    number: '0'
    run_exports:
        - libvpx >=1.7.0,<1.8.0a0
    string: h439df22_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 h04c84fa_2
        - binutils_linux-64 7.2.0 25
        - gcc_impl_linux-64 7.2.0 hc5ce805_2
        - gcc_linux-64 7.2.0 25
        - gxx_impl_linux-64 7.2.0 hd3faf3d_2
        - gxx_linux-64 7.2.0 25
        - libstdcxx-ng 7.2.0 h7a57d05_2
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - expat 2.2.5 he0dffb1_0
        - git 2.16.1 pl526hb75a9fb_1
        - libcurl 7.58.0 h1ad7b7a_0
        - libgcc-ng 7.2.0 h7cc24e2_2
        - libssh2 1.8.0 h9cfc8f7_4
        - libstdcxx-ng 7.2.0 h7a57d05_2
        - openssl 1.0.2n hb7f436b_0
        - perl 5.26.0 hae598fd_0
        - tk 8.6.7 hc745277_3
        - yasm 1.3.0 h99c0ef8_2
        - zlib 1.2.11 ha838bed_2
    run:
        - libgcc-ng >=7.2.0
        - libstdcxx-ng >=7.2.0
test:
    commands:
        - test -f ${PREFIX}/lib/libvpx.a
        - test -f ${PREFIX}/lib/libvpx.so
        - conda inspect linkages -p $PREFIX libvpx
about:
    description: 'libvpx is a free software video codec library from

        Google and the Alliance for Open Media (AOMedia).

        It serves as the reference software implementation for

        the video coding formats VP8 and VP9, and for AV1 a

        special fork named libaom that was stripped of

        backwards compatibility.

        '
    dev_url: https://chromium.googlesource.com/webm/libvpx
    doc_url: http://www.webmproject.org/vp9/
    home: https://www.webmproject.org/
    license: 3-clause BSD
    license_family: BSD
    summary: A high-quality, open video format for the web
extra:
    copy_test_source_files: true
    final: true
