boost_cpp: 1.68.0
c_compiler: gcc
c_compiler_version: '7'
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
cxx_compiler_version: '7'
docker_image: condaforge/linux-anvil-comp7
extend_keys:
- ignore_version
- ignore_build_only_deps
- extend_keys
- pin_run_as_build
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
libevent: 2.0.22
lua: '5'
numpy: '1.11'
openssl: 1.1.1a
perl: 5.26.0
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x.x
    max_pin: x.x.x
  boost-cpp:
    max_pin: x.x.x
  libevent:
    max_pin: x.x.x
  openssl:
    max_pin: x.x.x
  zlib:
    max_pin: x.x
python: '3.7'
r_base: '3.5'
target_platform: linux-64
zlib: '1.2'
