# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/graphite2-1.3.14-on-linux_64, last modified Thu Jun 25 19:38:53 2020
# ------------------------------------------------

package:
    name: graphite2
    version: 1.3.14
source:
    sha256: f99d1c13aa5fa296898a181dff9b82fb25f6cc0933dbaa7a475d8109bd54209d
    url: https://github.com/silnrsi/graphite/releases/download/1.3.14/graphite2-1.3.14.tgz
build:
    number: '0'
    run_exports:
        - graphite2 >=1.3.14,<2.0a0
    string: h23475e2_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - bzip2 1.0.8 h7b6447c_0
        - ca-certificates 2020.1.1 0
        - cmake 3.14.0 h52cb24c_0
        - expat 2.2.6 he6710b0_0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - krb5 1.17.1 h173b8e3_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libcurl 7.69.1 h20c2e04_0
        - libedit 3.1.20191231 h7b6447c_0
        - libgcc-ng 9.1.0 hdf63c60_0
        - libssh2 1.9.0 h1ba5d50_1
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - make 4.2.1 h1bed415_1
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - rhash 1.3.8 h1ba5d50_0
        - tk 8.6.10 hbc83047_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
about:
    home: http://graphite.sil.org/
    license: LGPLv2
    license_file: COPYING
    summary: A "smart font" system that handles the complexities of lesser-known languages
        of the world.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mingwandroid
        - ocefpaf
        - pkgw
