# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /root/project/packaging/torchvision, last modified Tue Jun 15 15:40:44 2021
# ------------------------------------------------

package:
  name: torchvision
  version: 0.10.0
source:
  path: /root/project
build:
  features: null
  script: python setup.py install --single-version-externally-managed --record=record.txt
  script_env:
    - BUILD_VERSION
    - CUDA_HOME
    - FORCE_CUDA
    - TORCH_CUDA_ARCH_LIST
  string: py38_cu111
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2021.5.25 h06a4308_1
    - ffmpeg 4.3 hf484d3e_0
    - freetype 2.10.4 h5ab3b9f_0
    - gmp 6.2.1 h2531618_2
    - gnutls 3.6.15 he1e5248_0
    - jpeg 9b h024ee3a_2
    - lame 3.100 h7b6447c_0
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libiconv 1.15 h63c8f33_5
    - libidn2 2.3.1 h27cfd23_0
    - libpng 1.6.37 hbc83047_0
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libtasn1 4.16.0 h27cfd23_0
    - libunistring 0.9.10 h27cfd23_0
    - nettle 3.7.3 hbbd107a_1
    - openh264 2.1.0 hd408876_0
    - zlib 1.2.11 h7b6447c_3
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - blas 1.0 mkl
    - ca-certificates 2021.5.25 h06a4308_1
    - certifi 2021.5.30 py38h06a4308_0
    - cudatoolkit 11.1.1 h6406543_8
    - intel-openmp 2021.2.0 h06a4308_610
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuv 1.40.0 h7b6447c_0
    - mkl 2021.2.0 h06a4308_296
    - ncurses 6.2 he6710b0_1
    - ninja 1.10.2 hff7bd54_1
    - openssl 1.1.1k h27cfd23_0
    - pip 21.1.2 py38h06a4308_0
    - python 3.8.10 h12debd9_8
    - pytorch 1.9.0 py3.8_cuda11.1_cudnn8.0.5_0
    - readline 8.1 h27cfd23_0
    - setuptools 52.0.0 py38h06a4308_0
    - sqlite 3.35.4 hdfb4753_0
    - tk 8.6.10 hbc83047_0
    - typing_extensions 3.7.4.3 pyha847dfd_0
    - wheel 0.36.2 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - cudatoolkit >=11.1,<11.2
    - ffmpeg >=4.2
    - jpeg <=9b
    - libpng
    - pillow >=5.3.0
    - python >=3.8,<3.9.0a0
    - pytorch==1.9.0
test:
  imports:
    - torchvision
    - torchvision.datasets
    - torchvision.transforms
  requires:
    - av
    - ca-certificates
    - jpeg <=9b
    - pytest
    - scipy
  source_files:
    - test
about:
  home: https://github.com/pytorch/vision
  license: BSD
  license_file: LICENSE
  summary: image and video datasets and models for torch deep learning
extra:
  copy_test_source_files: true
  final: true
