ignore_build_only_deps:
- numpy
- python
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  libboost:
    max_pin: x.x.x
extend_keys:
- ignore_version
- extend_keys
- ignore_build_only_deps
- pin_run_as_build
zlib:
- '1.2'
g2clib:
- '1.6'
serf:
- 1.3.9
boost:
- '1.73'
giflib:
- '5'
lzo:
- '2'
r_implementation:
- mro-base
- r-base
hdf5:
- 1.10.6
libpng:
- '1.6'
gst_plugins_base:
- '1.14'
libkml:
- '1.3'
llvm_variant:
- llvm
r_base:
- '3.5'
libxslt:
- '1.1'
pixman:
- '0.30'
expat:
- '2.2'
tk:
- '8.6'
libwebp:
- 1.0.0
qtwebkit:
- 'true'
libnetcdf:
- '4.6'
bzip2:
- '1.0'
proj4:
- 5.2.0
cyrus_sasl:
- 2.1.26
perl:
- '5.26'
fontconfig:
- '2.13'
proj:
- 6.2.1
python_impl:
- cpython
r_version:
- 3.5.0
cxx_compiler:
- gxx
boost_cpp:
- '1.73'
clang_variant:
- clang
cairo:
- '1.14'
rust_compiler:
- rust
openblas:
- 0.3.3
icu:
- '58'
hdfeos2:
- '2.20'
cran_mirror:
- https://mran.microsoft.com/snapshot/2018-01-01
VERBOSE_CM:
- VERBOSE=1
gstreamer:
- '1.14'
c_compiler:
- gcc
target_platform:
- linux-64
mpfr:
- '4'
apr:
- 1.6.3
rust_compiler_version:
- 1.46.0
jpeg:
- '9'
sqlite:
- '3'
libprotobuf:
- 3.11.2
libgd:
- 2.2.5
numpy:
- '1.16'
fortran_compiler:
- gfortran
glib:
- '2'
dbus:
- '1'
readline:
- '8.0'
openssl:
- 1.1.1
lua:
- '5'
noarch_python:
- python
gmp:
- '6.1'
channel_targets:
- defaults
blas_impl:
- openblas
- mkl
libgsasl:
- '1.8'
c_compiler_version:
- 7.5.0
mkl:
- '2021'
python_implementation:
- cpython
fortran_compiler_version:
- 7.5.0
cxx_compiler_version:
- 7.5.0
openjpeg:
- '2.3'
libtiff:
- '4.1'
libxml2:
- '2.9'
gnu:
- 2.12.2
VERBOSE_AT:
- V=1
hdf4:
- '4.2'
libffi:
- '3.3'
python:
- '3.8'
libgdal:
- '3.0'
cpu_optimization_target:
- nocona
geos:
- 3.8.0
xz:
- '5'
freetype:
- '2.10'
libdap4:
- '3.19'
harfbuzz:
- '2.4'
hdfeos5:
- '5.1'
zip_keys: []
