# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /feedstock/recipe, last modified Thu Mar 31 08:34:02 2022
# ------------------------------------------------

package:
  name: ca-certificates
  version: 2022.3.29
source:
  fn: cacert.pem
  sha256: 1979e7fe618c51ed1c9df43bba92f977a0d3fe7497ffa2a5e80dfc559a1e5a29
  url: https://curl.haxx.se/ca/cacert-2022-03-29.pem
build:
  number: '0'
  string: h06a4308_0
requirements:
  build: []
  run: []
test:
  commands:
    - pip check
  requires:
    - pip
about:
  doc_url: https://github.com/curl/curl/blob/master/docs/SSLCERTS.md
  home: https://github.com/conda-forge/ca-certificates-feedstock
  license: MPL-2.0
  license_file: LICENSE.txt
  summary: Certificates for use with other packages.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
