build_number_decrement: '0'
bzip2: '1'
c_compiler: gcc
channel_sources: conda-forge/label/gcc7,defaults
channel_targets: conda-forge gcc7
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
docker_image: conda/c3i-linux-64
fortran_compiler: gfortran
icu: '58'
ignore_build_only_deps: numpy
lua: '5'
numpy: '1.11'
perl: 5.26.0
pin_run_as_build:
  python: {min_pin: x.x, max_pin: x.x}
  r-base: {min_pin: x.x.x, max_pin: x.x.x}
  bzip2: {max_pin: x}
  icu: {max_pin: x}
  xz: {max_pin: x.x}
  zlib: {max_pin: x.x}
python: '3.6'
r_base: '3.5'
target_platform: linux-64
xz: '5.2'
zip_keys:
- [cxx_compiler, channel_sources, channel_targets, docker_image, build_number_decrement]
zlib: '1.2'
