# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Mon Oct 31 17:08:06 2022
# ------------------------------------------------

package:
  name: setuptools
  version: 65.5.0
source:
  patches:
    - patches/0002-disable-downloads-inside-conda-build.patch
    - patches/0021-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
  sha256: 512e5536220e38146176efb833d4a62aa726b7bbff82cfbc8ba9eaa3996e0b17
  url: https://pypi.io/packages/source/s/setuptools/setuptools-65.5.0.tar.gz
build:
  number: '0'
  string: py39h06a4308_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - patch 2.7.6 h7b6447c_1001
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - ca-certificates 2022.10.11 h06a4308_0
    - certifi 2022.9.24 py39h06a4308_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.3 he6710b0_2
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - ncurses 6.3 h5eee18b_3
    - openssl 1.1.1q h7f8727e_0
    - python 3.9.13 haa1d7c7_2
    - readline 8.2 h5eee18b_0
    - sqlite 3.39.3 h5082296_0
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2022e h04d1e81_0
    - xz 5.2.6 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
  run:
    - certifi >=2016.9.26
    - python >=3.9,<3.10.0a0
test:
  imports:
    - pkg_resources
    - setuptools
about:
  description: 'Setuptools is a fully-featured, actively-maintained, and stable library

    designed to facilitate packaging Python projects.

    '
  dev_url: https://github.com/pypa/setuptools
  doc_source_url: https://github.com/pypa/setuptools/tree/master/docs
  doc_url: https://setuptools.pypa.io/en/latest/
  home: https://github.com/pypa/setuptools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  license_url: https://github.com/pypa/setuptools/blob/main/LICENSE
  summary: Download, build, install, upgrade, and uninstall Python packages
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 6003d26b-cc17-40ee-85dc-bbb6ed82a1a4
  recipe-maintainers:
    - isuruf
    - jakirkham
    - msarahan
    - nicoddemus
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/setuptools-feedstock.git
  sha: bdafbdc52e8fd4fba83b4015ef9b163b6ebc9f16
