# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libunistring-0.9.10-on-linux_64, last modified Fri Apr  2 22:07:57 2021
# ------------------------------------------------

package:
  name: libunistring
  version: 0.9.10
source:
  fn: libunistring-0.9.10.tar.xz
  sha256: eb8fb2c3e4b6e2d336608377050892b54c3c983b646c561836550863003c05d7
  url: http://ftpmirror.gnu.org/libunistring/libunistring-0.9.10.tar.xz
build:
  number: '0'
  run_exports:
    - libunistring >=0,<1.0a0
  string: h27cfd23_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - binutils_impl_linux-64 2.33.1 he6710b0_7
    - binutils_linux-64 2.33.1 h9595d00_15
    - gcc_impl_linux-64 7.3.0 habb00fd_1
    - gcc_linux-64 7.3.0 h553295d_15
    - ld_impl_linux-64 2.33.1 h53a641e_7
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - make 4.2.1 h1bed415_1
  host:
    - _libgcc_mutex 0.1 main
    - libgcc-ng 9.1.0 hdf63c60_0
  run:
    - libgcc-ng >=7.3.0
test:
  commands:
    - test -e $PREFIX/lib/libunistring${SHLIB_EXT}
about:
  home: https://www.gnu.org/software/libunistring
  license: LGPL
  summary: This library provides functions for manipulating Unicode strings and for
    manipulating C strings according to the Unicode standard.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - bgruening
    - chenghlee
    - stefan-balke
