# This file created by conda-build 3.21.4
# ------------------------------------------------

package:
  name: libblas
  version: 3.9.0
source:
  patches:
    - patches/0001-Test-BLAS-and-LAPACKE-in-addition-to-LAPACK.patch
  sha256: 106087f1bb5f46afdfba7f569d0cbe23dacb9a07cd24733765a0e89dbe1ad573
  url: https://github.com/Reference-LAPACK/lapack/archive/v3.9.0.tar.gz
build:
  number: 11
  run_exports:
    - libblas >=3.9.0,<4.0a0
  string: 11_linux64_openblas
  track_features: null
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_llvm
    - libgcc-ng 11.1.0 hc902ee8_8
    - libgfortran-ng 11.1.0 h69a702a_8
    - libgfortran5 11.1.0 h6c583b3_8
    - libopenblas 0.3.17 pthreads_h8fe5266_1
    - llvm-openmp 12.0.1 h4bd325d_1
  run:
    - libopenblas >=0.3.17,<0.3.18.0a0
    - libopenblas >=0.3.17,<1.0a0
  run_constrained:
    - blas * openblas
    - libcblas 3.9.0 11_linux64_openblas
    - liblapack 3.9.0 11_linux64_openblas
    - liblapacke 3.9.0 11_linux64_openblas
test:
  commands:
    - test -f $PREFIX/lib/libblas.so.3
about:
  home: https://github.com/conda-forge/blas-feedstock
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
  summary: Metapackage to select the BLAS variant. Use conda's pinning mechanism in
    your environment to control which variant you want.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - h-vetinari
    - isuruf
    - jakirkham
    - ocefpaf
    - pelson
