# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Wed Jun 23 19:49:45 2021
# ------------------------------------------------

package:
  name: pcre
  version: '8.45'
source:
  patches:
    - 0001-Define-snprintf-for-old-VS.patch
    - 0002-Workaround-CMake-FIND_PACKAGE-looking-on-PATH-misfeature.patch
  sha256: 4e6ce03e0336e8b4a3d6c2b70b1c5e18590a5673a98186da90d4f33c23defc09
  url: https://ftp.pcre.org/pub/pcre/pcre-8.45.tar.gz
build:
  number: '0'
  run_exports:
    - pcre >=8.45,<9.0a0
  string: h295c915_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - gcc_impl_linux-64 7.5.0 h7105cf2_17
    - gcc_linux-64 7.5.0 h8f34230_30
    - gxx_impl_linux-64 7.5.0 h0a5bf11_17
    - gxx_linux-64 7.5.0 hffc177d_30
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libgcc-devel_linux-64 7.5.0 hbbeae57_17
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-devel_linux-64 7.5.0 hf0c5c8d_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libtool 2.4.6 h7b6447c_1005
    - make 4.2.1 h1bed415_1
    - patch 2.7.6 h7b6447c_1001
    - pkg-config 0.29.2 h1bed415_8
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
  run:
    - libgcc-ng >=7.5.0
    - libstdcxx-ng >=7.5.0
test:
  commands:
    - pcre-config --version
    - pcregrep --help
    - pcretest --help
    - test -f "${PREFIX}/include/pcre.h"
    - test -f "${PREFIX}/include/pcre_scanner.h"
    - test -f "${PREFIX}/include/pcre_stringpiece.h"
    - test -f "${PREFIX}/include/pcrecpp.h"
    - test -f "${PREFIX}/include/pcrecpparg.h"
    - test -f "${PREFIX}/include/pcreposix.h"
    - test -f "${PREFIX}/lib/libpcre.a"
    - test -f "${PREFIX}/lib/libpcre${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/libpcrecpp.a"
    - test -f "${PREFIX}/lib/libpcrecpp${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/libpcreposix.a"
    - test -f "${PREFIX}/lib/libpcreposix${SHLIB_EXT}"
about:
  description: 'PCRE implement regular expression pattern matching using the same
    syntax and

    semantics as Perl 5. PCRE has its own native API, as well as a set of wrapper

    functions that correspond to the POSIX regular expression API.

    '
  dev_url: http://vcs.pcre.org/pcre2/
  doc_source_url: https://vcs.pcre.org/pcre2/code/trunk/doc/?sortdir=down
  doc_url: http://www.pcre.org/original/doc/html/
  home: http://www.pcre.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENCE
  summary: Regular expression pattern matching using the same syntax and semantics
    as Perl 5.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - chenghlee
    - jakirkham
    - ocefpaf
    - saraedum
    - scopatz
    - sebastian-luna-valero
