# This file created by conda-build 3.21.8
# ------------------------------------------------

package:
  name: libgfortran5
  version: 12.1.0
source:
  - patches:
      - patches/0021-Hardcode-HAVE_ALIGNED_ALLOC-1-in-libstdc-v3-configur.patch
      - patches/new-allow-commands-in-main-specfile.patch
    sha256: e88a004a14697bbbaba311f38a938c716d9a652fd151aaaa4cf1b5b99b90e2de
    url: https://ftp.gnu.org/gnu/gcc/gcc-12.1.0/gcc-12.1.0.tar.gz
build:
  detect_binary_files_with_prefix: false
  ignore_run_exports:
    - __glibc
  missing_dso_whitelist:
    - '*'
  number: 16
  string: hdcd56e2_16
requirements:
  build:
    - binutils_impl_linux-64 2.36.1 h193b22a_2
    - gcc_bootstrap_linux-64 11.2.0 h6cd0796_9
    - kernel-headers_linux-64 2.6.32 he073ed8_15
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - sysroot_linux-64 2.12 he073ed8_15
  host:
    - kernel-headers_linux-64 2.6.32 he073ed8_15
    - sysroot_linux-64 2.12 he073ed8_15
  run: []
  run_constrained:
    - libgfortran-ng 12.1.0
test:
  commands:
    - test -f ${PREFIX}/lib/libgfortran.so
about:
  home: https://gcc.gnu.org/
  license: GPL-3.0-only WITH GCC-exception-3.1
  summary: The GNU Fortran Runtime Library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - beckermr
    - isuruf
    - timsnyder
    - xhochy
