# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /root/project/packaging/torchaudio, last modified Tue Jun 15 13:16:56 2021
# ------------------------------------------------

package:
  name: torchaudio
  version: 0.9.0
source:
  path: /root/project
build:
  string: py36
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - blas 1.0 mkl
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2021.5.25 h06a4308_1
    - certifi 2021.5.30 py36h06a4308_0
    - cmake 3.19.6 h973ab73_0
    - cpuonly 1.0 0
    - dataclasses 0.8 pyh4f3eec9_6
    - expat 2.4.1 h2531618_2
    - intel-openmp 2021.2.0 h06a4308_610
    - krb5 1.18.2 h173b8e3_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libcurl 7.71.1 h20c2e04_1
    - libedit 3.1.20210216 h27cfd23_1
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libssh2 1.9.0 h1ba5d50_1
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuv 1.40.0 h7b6447c_0
    - lz4-c 1.9.3 h2531618_0
    - mkl 2020.2 256
    - mkl-service 2.3.0 py36he8ac12f_0
    - mkl_fft 1.3.0 py36h54f3939_0
    - mkl_random 1.1.1 py36h0573a6f_0
    - ncurses 6.2 he6710b0_1
    - ninja 1.10.2 hff7bd54_1
    - numpy 1.19.2 py36h54aff64_0
    - numpy-base 1.19.2 py36hfa32c7d_0
    - openssl 1.1.1k h27cfd23_0
    - pip 21.1.2 py36h06a4308_0
    - python 3.6.13 h12debd9_1
    - pytorch 1.9.0 py3.6_cpu_0
    - readline 8.1 h27cfd23_0
    - rhash 1.4.1 h3c74f83_1
    - setuptools 52.0.0 py36h06a4308_0
    - six 1.15.0 py36h06a4308_0
    - sqlite 3.35.4 hdfb4753_0
    - tk 8.6.10 hbc83047_0
    - typing_extensions 3.7.4.3 pyha847dfd_0
    - wheel 0.36.2 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
    - zstd 1.4.9 haebb681_0
  run:
    - defaults::numpy >=1.11
    - python >=3.6,<3.7.0a0
    - pytorch==1.9.0
test:
  imports:
    - torchaudio
    - torchaudio.datasets
    - torchaudio.kaldi_io
    - torchaudio.sox_effects
    - torchaudio.transforms
  requires:
    - cpuonly
    - pytest
    - scipy
  source_files:
    - test
about:
  home: https://github.com/pytorch/audio
  license: BSD
  license_file: LICENSE
  summary: simple audio I/O for pytorch
extra:
  copy_test_source_files: true
  final: true
