# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /builder/conda/pytorch-nightly, last modified Fri Jun 11 21:50:51 2021
# ------------------------------------------------

package:
  name: pytorch
  version: 1.9.0
source:
  path: /pytorch
build:
  detect_binary_files_with_prefix: false
  features: null
  number: '0'
  script_env:
    - BUILD_SPLIT_CUDA
    - BUILD_TEST
    - CMAKE_ARGS
    - CMAKE_OSX_ARCHITECTURES
    - CONDA_CUDATOOLKIT_CONSTRAINT
    - CUDA_VERSION
    - CUDNN_VERSION
    - DEBUG
    - DEVELOPER_DIR
    - EXTRA_CAFFE2_CMAKE_FLAGS
    - USE_CUDA
    - USE_DISTRIBUTED
    - USE_FBGEMM
    - USE_GLOO_WITH_OPENSSL
    - USE_MKLDNN
    - USE_NNPACK
    - USE_QNNPACK
    - USE_WHOLE_CUDNN
  string: py3.9_cuda11.1_cudnn8.0.5_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2021.5.25 h06a4308_1
    - cmake 3.19.6 h973ab73_0
    - expat 2.4.1 h2531618_2
    - krb5 1.18.2 h173b8e3_0
    - libcurl 7.71.1 h20c2e04_1
    - libedit 3.1.20210216 h27cfd23_1
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libssh2 1.9.0 h1ba5d50_1
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuv 1.40.0 h7b6447c_0
    - lz4-c 1.9.3 h2531618_0
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1k h27cfd23_0
    - rhash 1.4.1 h3c74f83_1
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
    - zstd 1.4.9 haebb681_0
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - blas 1.0 mkl
    - ca-certificates 2021.5.25 h06a4308_1
    - certifi 2021.5.30 py39h06a4308_0
    - intel-openmp 2021.2.0 h06a4308_610
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuv 1.40.0 h7b6447c_0
    - magma-cuda111 2.5.2 1
    - mkl 2020.2 256
    - mkl-include 2021.2.0 h06a4308_296
    - mkl-service 2.3.0 py39he8ac12f_0
    - mkl_fft 1.3.0 py39h54f3939_0
    - mkl_random 1.0.2 py39h63df603_0
    - ncurses 6.2 he6710b0_1
    - ninja 1.10.2 hff7bd54_1
    - numpy 1.19.2 py39h89c1606_0
    - numpy-base 1.19.2 py39h2ae0177_0
    - openssl 1.1.1k h27cfd23_0
    - pip 21.1.2 py39h06a4308_0
    - pkg-config 0.29.2 h1bed415_8
    - python 3.9.5 h12debd9_4
    - pyyaml 5.4.1 py39h27cfd23_1
    - readline 8.1 h27cfd23_0
    - setuptools 52.0.0 py39h06a4308_0
    - six 1.15.0 py39h06a4308_0
    - sqlite 3.35.4 hdfb4753_0
    - tk 8.6.10 hbc83047_0
    - typing_extensions 3.7.4.3 pyha847dfd_0
    - tzdata 2020f h52ac0ba_0
    - wheel 0.36.2 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - yaml 0.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - blas * mkl
    - cudatoolkit >=11.1,<11.2
    - libuv >=1.40.0,<2.0a0
    - mkl >=2018
    - ninja
    - python >=3.9,<3.10.0a0
    - typing_extensions
test:
  commands:
    - OMP_NUM_THREADS=4 python ./test/run_test.py || true
  imports:
    - torch
  source_files:
    - test
about:
  home: http://pytorch.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: PyTorch is an optimized tensor library for deep learning using GPUs and
    CPUs.
extra:
  copy_test_source_files: true
  final: true
