# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/ca-certificates-2022.3.18-on-linux_64, last modified Wed Mar 23 08:38:01 2022
# ------------------------------------------------

package:
  name: ca-certificates
  version: 2022.3.18
source:
  fn: cacert.pem
  sha256: 2d0575e481482551a6a4f9152e7d2ab4bafaeaee5f2606edb829c2fdb3713336
  url: https://curl.haxx.se/ca/cacert-2022-03-18.pem
build:
  number: '0'
  string: h06a4308_0
requirements:
  build: []
  run: []
test:
  commands:
    - pip check
  requires:
    - pip
about:
  doc_url: https://github.com/curl/curl/blob/master/docs/SSLCERTS.md
  home: https://github.com/conda-forge/ca-certificates-feedstock
  license: MPL-2.0
  license_file: LICENSE.txt
  summary: Certificates for use with other packages.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
