# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /feedstock/recipe, last modified Tue May 31 11:24:13 2022
# ------------------------------------------------

package:
  name: gmp
  version: 6.2.1
source:
  patches:
    - 0000-Avoid-the-x18-register.patch
  sha256: eae9326beb4158c386e39a356818031bd28f3124cf915f8c5b1dc4c7a36b4d7c
  url: https://gmplib.org/download/gmp/gmp-6.2.1.tar.bz2
build:
  number: '3'
  run_exports:
    - gmp >=6.2.1,<7.0a0
  string: h295c915_3
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - gcc_impl_linux-64 7.5.0 h7105cf2_17
    - gcc_linux-64 7.5.0 h8f34230_30
    - gnuconfig 2021.05.24 hd3eb1b0_0
    - gxx_impl_linux-64 7.5.0 h0a5bf11_17
    - gxx_linux-64 7.5.0 hffc177d_30
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libgcc-devel_linux-64 7.5.0 hbbeae57_17
    - libgcc-ng 11.2.0 h1234567_0
    - libgomp 11.2.0 h1234567_0
    - libstdcxx-devel_linux-64 7.5.0 hf0c5c8d_17
    - libstdcxx-ng 11.2.0 h1234567_0
    - m4 1.4.18 h4e445db_0
    - make 4.2.1 h1bed415_1
    - patch 2.7.6 h7b6447c_1001
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - libgcc-ng 11.2.0 h1234567_0
    - libgomp 11.2.0 h1234567_0
    - libstdcxx-ng 11.2.0 h1234567_0
  run:
    - libgcc-ng >=7.5.0
    - libstdcxx-ng >=7.5.0
test:
  commands:
    - test -f ${PREFIX}/lib/libgmp.a
    - test -f ${PREFIX}/lib/libgmp.so
    - test -f ${PREFIX}/lib/libgmpxx.a
    - test -f ${PREFIX}/lib/libgmpxx.so
  files:
    - test.c
  requires:
    - gcc_linux-64 7.5.0.*
about:
  dev_url: https://gmplib.org/repo/
  doc_url: https://gmplib.org/manual/
  home: https://gmplib.org/
  license: GPL-2.0-or-later AND LGPL-3.0-or-later
  license_file: COPYING.LESSERv3
  summary: The GNU multiprecision library.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 1f864de9-17d0-4df7-8f6e-919e78670a65
  recipe-maintainers:
    - asmeurer
    - isuruf
    - jakirkham
  remote_url: git@github.com:AnacondaRecipes/gmp-feedstock.git
  sha: 63ab58db0e06c67eb0ed0853ba4544bdd5f0c1d9
