# This file created by conda-build 3.21.6
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Nov 13 14:36:49 2021
# ------------------------------------------------

package:
  name: jupyter_core
  version: 4.9.1
source:
  sha256: dce8a7499da5a53ae3afd5a9f4b02e5df1d57250cf48f3ad79da23b4778cd6fa
  url: https://pypi.io/packages/source/j/jupyter_core/jupyter_core-4.9.1.tar.gz
build:
  entry_points:
    - jupyter = jupyter_core.command:main
    - jupyter-migrate = jupyter_core.migrate:main
    - jupyter-troubleshoot = jupyter_core.troubleshoot:main
  number: '1'
  script: /home/conda/feedstock_root/build_artifacts/jupyter_core_1636814264288/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
    -m pip install . --no-deps -vv
  string: py37h89c1867_1
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.10.8 ha878542_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 11.2.0 h1d223b6_11
    - libgomp 11.2.0 h1d223b6_11
    - libnsl 2.0.0 h7f98852_0
    - libstdcxx-ng 11.2.0 he4da1e4_11
    - libzlib 1.2.11 h36c2ea0_1013
    - ncurses 6.2 h58526e2_4
    - openssl 3.0.0 h7f98852_2
    - pip 21.3.1 pyhd8ed1ab_0
    - python 3.7.12 hf930737_100_cpython
    - python_abi 3.7 2_cp37m
    - readline 8.1 h46c0cb4_0
    - setuptools 58.5.3 py37h89c1867_0
    - sqlite 3.36.0 h9cd32fc_2
    - tk 8.6.11 h27826a3_1
    - wheel 0.37.0 pyhd8ed1ab_1
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h36c2ea0_1013
  run:
    - python >=3.7,<3.8.0a0
    - python_abi 3.7.* *_cp37m
    - traitlets
test:
  commands:
    - jupyter -h
    - jupyter-migrate -h
    - jupyter-troubleshoot --help
    - python -m pytest --pyargs jupyter_core -k "not test_not_on_path and not test_path_priority"
    - pip check
  imports:
    - jupyter_core
  requires:
    - nose
    - pip
    - pytest
about:
  dev_url: https://github.com/jupyter/jupyter_core
  doc_source_url: https://github.com/jupyter/jupyter_core/tree/master/docs
  doc_url: https://jupyter-core.readthedocs.io
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: Core common functionality of Jupyter projects.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - Carreau
    - bollwyvl
    - jakirkham
    - jasongrout
    - minrk
    - ocefpaf
    - pelson
