# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Thu Aug 19 13:57:01 2021
# ------------------------------------------------

package:
  name: glib
  version: 2.69.1
source:
  patches:
    - patches/0001-replace-hardcoded-paths.patch
    - patches/0002-skip-some-tests.patch
    - patches/0003-add-install_rpath-to-meson-build-files.patch
  sha256: f92f34057a091fc8638d91f10cece842cb8618e9a1090b0ddb19cc15a21bf39c
  url: http://ftp.gnome.org/pub/GNOME/sources/glib/2.69/glib-2.69.1.tar.xz
build:
  number: '0'
  run_exports:
    - glib >=2.69.1,<3.0a0
  string: h5202010_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - ca-certificates 2021.7.5 h06a4308_1
    - certifi 2021.5.30 py39h06a4308_0
    - gcc_impl_linux-64 7.5.0 h7105cf2_17
    - gcc_linux-64 7.5.0 h8f34230_30
    - gxx_impl_linux-64 7.5.0 h0a5bf11_17
    - gxx_linux-64 7.5.0 hffc177d_30
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-devel_linux-64 7.5.0 hbbeae57_17
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-devel_linux-64 7.5.0 hf0c5c8d_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - meson 0.59.0 pyhd3eb1b0_0
    - ncurses 6.2 he6710b0_1
    - ninja 1.10.2 hff7bd54_1
    - openssl 1.1.1k h27cfd23_0
    - patch 2.7.6 h7b6447c_1001
    - pkg-config 0.29.2 h1bed415_8
    - python 3.9.6 h12debd9_0
    - readline 8.1 h27cfd23_0
    - setuptools 52.0.0 py39h06a4308_0
    - sqlite 3.36.0 hc218d9a_0
    - sysroot_linux-64 2.17 h57e8cba_10
    - tk 8.6.10 hbc83047_0
    - tzdata 2021a h5d7bf9c_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.7.5 h06a4308_1
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1k h27cfd23_0
    - pcre 8.45 h295c915_0
    - python 3.8.11 h12debd9_0_cpython
    - readline 8.1 h27cfd23_0
    - sqlite 3.36.0 hc218d9a_0
    - tk 8.6.10 hbc83047_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - libffi >=3.3,<3.4.0a0
    - libgcc-ng >=7.5.0
    - libstdcxx-ng >=7.5.0
    - pcre >=8.45,<9.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libglib-2.0.so
    - test ! -f ${PREFIX}/lib/libgobject-2.0.la
    - gapplication help
    - gdbus help
    - gio version
    - gio-querymodules .
    - glib-compile-resources --help
    - glib-compile-schemas --help
    - gobject-query --help
    - gresource help
    - gtester --help
about:
  description: 'GLib provides the core application building blocks for libraries and

    applications written in C. It provides the core object system used in

    GNOME, the main loop implementation, and a large set of utility functions

    functions for strings and common data structures.

    '
  dev_url: https://git.gnome.org/browse/glib/
  doc_source_url: https://git.gnome.org/browse/glib/tree/docs
  doc_url: https://developer.gnome.org/glib/unstable/
  home: https://developer.gnome.org/glib/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: Provides core application building blocks for libraries and applications
    written in C.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ccordoba12
    - chenghlee
    - isuruf
    - jakirkham
    - ocefpaf
    - pkgw
    - scopatz
