# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Dec  8 10:33:11 2020
# ------------------------------------------------

package:
    name: pandas
    version: 1.1.5
source:
    sha256: f10fc41ee3c75a474d3bdf68d396f10782d013d7f67db99c0efbfd0acb99701b
    url: https://github.com/pandas-dev/pandas/releases/download/v1.1.5/pandas-1.1.5.tar.gz
build:
    number: '0'
    script:
        - /home/conda/feedstock_root/build_artifacts/pandas_1607423650243/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
            -m pip install -vv --no-deps --ignore-installed . --global-option="build_ext"
            --global-option="-j${CPU_COUNT}" --no-use-pep517
    string: py36h284efc9_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-64 2.35.1 h17ad2fc_0
        - binutils_linux-64 2.35 hc3fd857_29
        - gcc_impl_linux-64 9.3.0 h28f5a38_17
        - gcc_linux-64 9.3.0 h7247604_29
        - gxx_impl_linux-64 9.3.0 h53cdd4c_17
        - gxx_linux-64 9.3.0 h0d07fa4_29
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.35.1 hed1e6ac_0
        - libgcc-devel_linux-64 9.3.0 hfd08b2a_17
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-devel_linux-64 9.3.0 h4084dd6_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - sysroot_linux-64 2.12 h77966d4_13
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.12.5 ha878542_0
        - certifi 2020.12.5 py36h5fab9bb_0
        - cython 0.29.21 py36ha357f81_1
        - ld_impl_linux-64 2.35.1 hed1e6ac_0
        - libblas 3.9.0 3_openblas
        - libcblas 3.9.0 3_openblas
        - libffi 3.3 h58526e2_2
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgfortran-ng 9.3.0 he4bcb1c_17
        - libgfortran5 9.3.0 he4bcb1c_17
        - libgomp 9.3.0 h5dbcf3e_17
        - liblapack 3.9.0 3_openblas
        - libopenblas 0.3.12 pthreads_h4812303_1
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 h58526e2_4
        - numpy 1.16.5 py36h2aa4a07_1
        - openssl 1.1.1h h516909a_0
        - pip 20.3.1 pyhd8ed1ab_0
        - python 3.6.11 hffdb5ce_3_cpython
        - python_abi 3.6 1_cp36m
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py36h9880bd3_2
        - sqlite 3.34.0 h74cdb3f_0
        - tk 8.6.10 hed695b0_1
        - wheel 0.36.1 pyhd3deb0d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1010
    run:
        - libgcc-ng >=9.3.0
        - libstdcxx-ng >=9.3.0
        - numpy >=1.16.5,<2.0a0
        - python >=3.6,<3.7.0a0
        - python-dateutil >=2.7.3
        - python_abi 3.6.* *_cp36m
        - pytz >=2017.2
test:
    imports:
        - pandas
about:
    home: http://pandas.pydata.org
    license: BSD-3-Clause
    license_file: LICENSE
    summary: High-performance, easy-to-use data structures and data analysis tools.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - TomAugspurger
        - WillAyd
        - jorisvandenbossche
        - jreback
        - msarahan
        - ocefpaf
