# This file created by conda-build 3.13.0
# ------------------------------------------------

package:
    name: py-opencv
    version: 3.4.2
source:
    -   fn: opencv-3.4.2.zip
        patches:
            - 0001-Use-OpenCV_INSTALL_BINARIES_PREFIX-instead-of-hardcoding.patch
            - 0002-Fix-protobuf-Parser-call.patch
        sha256: 9405c5d7d8ab1696e98631d0c92125816356ec366a73c417bdcc4d74783b42aa
        url: https://github.com/opencv/opencv/archive/3.4.2.zip
    -   fn: opencv_contrib-3.4.2.tar.gz
        folder: opencv_contrib-3.4.2
        sha256: 45a52764ebd2558fa0b7fd8dc47379b37dd0956d912abbf7c786228374fdf60d
        url: https://github.com/opencv/opencv_contrib/archive/3.4.2.tar.gz
build:
    ignore_run_exports:
        - ffmpeg
        - freetype
        - harfbuzz
        - hdf5
        - jasper
        - jpeg
        - libpng
        - libprotobuf
        - libtiff
        - zlib
    number: 1
    run_exports:
        - py-opencv >=3.4.2,<3.5.0a0
    string: py37hb342d67_1
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - bzip2 1.0.6 h14c3975_5
        - ca-certificates 2018.03.07 0
        - cmake 3.12.0 h307fef2_0
        - expat 2.2.6 he6710b0_0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_3
        - libcurl 7.61.0 h1ad7b7a_0
        - libgcc-ng 8.2.0 hdf63c60_1
        - libssh2 1.8.0 h9cfc8f7_4
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - make 4.2.1 h1bed415_1
        - ncurses 6.1 hf484d3e_0
        - openssl 1.0.2p h14c3975_0
        - pkg-config 0.29.2 h1bed415_8
        - rhash 1.3.6 hb7f436b_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 ha838bed_2
    host:
        - blas 1.0 mkl
        - bzip2 1.0.6 h14c3975_5
        - ca-certificates 2018.03.07 0
        - cairo 1.14.12 h8948797_3
        - eigen 3.3.3 h5721d7b_0
        - ffmpeg 4.0 hcdf2ecd_0
        - fontconfig 2.13.0 h9420a91_0
        - freeglut 3.0.0 hf484d3e_5
        - freetype 2.9.1 h8a8886c_1
        - glib 2.56.2 hd408876_0
        - graphite2 1.3.12 h23475e2_2
        - harfbuzz 1.7.6 hec2c2bc_3
        - hdf5 1.10.2 hba1933b_1
        - icu 58.2 h9c2bf20_1
        - intel-openmp 2018.0.3 0
        - jasper 2.0.14 h07fcdf6_1
        - jpeg 9b h024ee3a_2
        - libedit 3.1.20170329 h6b74fdf_2
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libglu 9.0.0 hf484d3e_1
        - libopencv 3.4.2 hb342d67_1
        - libopus 1.2.1 hb9ed12e_0
        - libpng 1.6.34 hb9fc6fc_0
        - libprotobuf 3.5.2 h6f1eeef_0
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - libtiff 4.0.9 he85c1e1_2
        - libuuid 1.0.3 h1bed415_2
        - libvpx 1.7.0 h439df22_0
        - libxcb 1.13 h1bed415_1
        - libxml2 2.9.8 h26e45fe_1
        - mkl 2018.0.3 1
        - ncurses 6.1 hf484d3e_0
        - numpy 1.11.3 py37h1d66e8a_10
        - numpy-base 1.11.3 py37h81de0dd_10
        - openssl 1.0.2p h14c3975_0
        - pcre 8.42 h439df22_0
        - pixman 0.34.0 hceecf20_3
        - python 3.7.0 hc3d631a_0
        - readline 7.0 h7b6447c_5
        - sqlite 3.24.0 h84994c4_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 ha838bed_2
    run:
        - libgcc-ng >=7.3.0
        - libopencv 3.4.2 hb342d67_1
        - libstdcxx-ng >=7.3.0
        - numpy >=1.11.3,<2.0a0
        - python >=3.7,<3.8.0a0
test:
    imports:
        - cv2
        - cv2.xfeatures2d
    requires:
        - gxx_linux-64 7.3.0.*
about:
    description: 'OpenCV (Open Source Computer Vision Library) includes several hundreds
        of computer vision algorithms.

        It has a modular structure,which means that the package includes several shared
        or static libraries.

        '
    doc_source_url: https://github.com/opencv/opencv/tree/master/doc
    doc_url: http://docs.opencv.org/
    home: http://opencv.org/
    license: BSD 3-clause
    license_family: BSD
    summary: Computer vision and machine learning software library.
extra:
    copy_test_source_files: true
    final: true
