# This file created by conda-build 3.16.3
# meta.yaml template originally from:
# /builder/conda/pytorch-1.1.0, last modified Tue Apr 30 19:39:42 2019
# ------------------------------------------------

package:
    name: pytorch
    version: 1.1.0
source:
    path: /pytorch
build:
    detect_binary_files_with_prefix: false
    number: '0'
    script_env:
        - CMAKE_ARGS
        - CONDA_CUDATOOLKIT_CONSTRAINT
        - CUDA_VERSION
        - CUDNN_VERSION
        - DEBUG
        - DEVELOPER_DIR
        - EXTRA_CAFFE2_CMAKE_FLAGS
        - NO_CUDA
        - NO_FBGEMM
    string: py2.7_cuda10.0.130_cudnn7.5.1_0
requirements:
    build:
        - krb5 1.16.1 h173b8e3_7
        - libssh2 1.8.2 h1ba5d50_0
        - rhash 1.3.8 h1ba5d50_0
        - cmake 3.14.0 h52cb24c_0
        - libedit 3.1.20181209 hc058e9b_0
        - ncurses 6.1 he6710b0_1
        - expat 2.2.6 he6710b0_0
        - openssl 1.1.1b h7b6447c_1
        - xz 5.2.4 h14c3975_4
        - libcurl 7.64.1 h20c2e04_0
        - ca-certificates 2019.1.23 0
        - libgcc-ng 8.2.0 hdf63c60_1
        - tk 8.6.8 hbc83047_0
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - zlib 1.2.11 h7b6447c_3
        - bzip2 1.0.6 h14c3975_5
    host:
        - sqlite 3.28.0 h7b6447c_0
        - magma-cuda100 2.5.0 1
        - blas 1.0 mkl
        - pycparser 2.19 py27_0
        - pip 19.1 py27_0
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - yaml 0.1.7 had09818_2
        - mkl 2019.3 199
        - python 2.7.16 h9bab390_0
        - tk 8.6.8 hbc83047_0
        - typing 3.6.6 py27_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - certifi 2019.3.9 py27_0
        - numpy 1.11.3 py27h7e9f1db_12
        - wheel 0.33.1 py27_0
        - ncurses 6.1 he6710b0_1
        - cffi 1.12.3 py27h2e261b9_0
        - numpy-base 1.11.3 py27hde5b4d6_12
        - ca-certificates 2019.1.23 0
        - libgcc-ng 8.2.0 hdf63c60_1
        - libffi 3.2.1 hd88cf55_4
        - ninja 1.9.0 py27hfd86e86_0
        - readline 7.0 h7b6447c_5
        - pyyaml 5.1 py27h7b6447c_0
        - libedit 3.1.20181209 hc058e9b_0
        - zlib 1.2.11 h7b6447c_3
        - openssl 1.1.1b h7b6447c_1
        - intel-openmp 2019.3 199
        - mkl-include 2019.3 199
        - setuptools 41.0.1 py27_0
    run:
        - cffi
        - cudatoolkit >=10.0,<10.1
        - future
        - mkl >=2018
        - ninja
        - numpy >=1.11
        - python >=2.7,<2.8.0a0
test:
    commands:
        - OMP_NUM_THREADS=4 python ./test/run_test.py || true
    imports:
        - torch
    source_files:
        - test
about:
    home: http://pytorch.org/
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: PyTorch is an optimized tensor library for deep learning using GPUs and
        CPUs.
extra:
    copy_test_source_files: true
    final: true
