# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/ca-certificates-2022.2.1-on-linux_64, last modified Mon Feb 28 15:28:11 2022
# ------------------------------------------------

package:
  name: ca-certificates
  version: 2022.2.1
source:
  fn: cacert.pem
  sha256: 1d9195b76d2ea25c2b5ae9bee52d05075244d78fcd9c58ee0b6fac47d395a5eb
  url: https://curl.haxx.se/ca/cacert-2022-02-01.pem
build:
  number: '0'
  string: h06a4308_0
requirements:
  build: []
  run: []
test:
  commands:
    - pip check
  requires:
    - pip
about:
  doc_url: https://github.com/curl/curl/blob/master/docs/SSLCERTS.md
  home: https://github.com/conda-forge/ca-certificates-feedstock
  license: MPL-2.0
  license_file: LICENSE.txt
  summary: Certificates for use with other packages.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
