# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libtasn1-4.16.0-on-linux_64, last modified Fri Apr  2 23:13:36 2021
# ------------------------------------------------

package:
  name: libtasn1
  version: 4.16.0
source:
  fn: libtasn1-4.16.0.tar.gz
  patches: null
  sha256: 0e0fb0903839117cb6e3b56e68222771bebf22ad7fc2295a0ed7d576e8d4329d
  url: http://ftp.gnu.org/gnu/libtasn1/libtasn1-4.16.0.tar.gz
build:
  number: '0'
  run_exports:
    - libtasn1 >=4.16.0,<5.0a0
  string: h27cfd23_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - binutils_impl_linux-64 2.33.1 he6710b0_7
    - binutils_linux-64 2.33.1 h9595d00_15
    - gcc_impl_linux-64 7.3.0 habb00fd_1
    - gcc_linux-64 7.3.0 h553295d_15
    - ld_impl_linux-64 2.33.1 h53a641e_7
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - make 4.2.1 h1bed415_1
  host:
    - _libgcc_mutex 0.1 main
    - libgcc-ng 9.1.0 hdf63c60_0
  run:
    - libgcc-ng >=7.3.0
test:
  commands:
    - test -f $PREFIX/lib/libtasn1${SHLIB_EXT}
    - conda inspect linkages -p $PREFIX $PKG_NAME
about:
  description: 'The Libtasn1 library provides Abstract Syntax Notation One

    (ASN.1, as specified by the X.680 ITU-T recommendation) parsing and structures
    management,

    and Distinguished Encoding Rules (DER, as per X.690) encoding and decoding functions.

    '
  dev_url: https://gitlab.com/gnutls/libtasn1/
  doc_url: https://www.gnu.org/software/libtasn1/manual/libtasn1.html
  home: https://www.gnu.org/software/libtasn1/
  license: GPL-3.0
  license_file: LICENSE
  summary: Libtasn1 is the ASN.1 library used by GnuTLS, p11-kit and some other packages
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ceholden
    - chenghlee
    - gillins
    - ocefpaf
