# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/cairo-1.16.0-on-linux_64, last modified Tue Mar  9 02:52:13 2021
# ------------------------------------------------

package:
  name: cairo
  version: 1.16.0
source:
  sha256: 5e7b29b3f113ef870d1e3ecf8adf21f923396401604bda16d44be45e66052331
  url: http://cairographics.org/releases/cairo-1.16.0.tar.xz
build:
  number: '1'
  run_exports:
    - cairo >=1.16.0,<2.0a0
  string: hf32fb01_1
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - autoconf 2.69 pl526hebd4dad_5
    - automake 1.16.2 pl526_0
    - binutils_impl_linux-64 2.33.1 he6710b0_7
    - binutils_linux-64 2.33.1 h9595d00_15
    - ca-certificates 2021.1.19 h06a4308_1
    - gcc_impl_linux-64 7.3.0 habb00fd_1
    - gcc_linux-64 7.3.0 h553295d_15
    - gxx_impl_linux-64 7.3.0 hdf63c60_1
    - gxx_linux-64 7.3.0 h553295d_15
    - ld_impl_linux-64 2.33.1 h53a641e_7
    - libedit 3.1.20191231 h14c3975_1
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - libtool 2.4.6 h7b6447c_1005
    - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
    - libx11-cos6-x86_64 1.6.4 h64a1553_0
    - libx11-devel-cos6-x86_64 1.6.4 hb9851ce_0
    - libxau-cos6-x86_64 1.0.6 h4888106_0
    - libxau-devel-cos6-x86_64 1.0.6 hf5ff492_0
    - libxext-cos6-x86_64 1.3.3 hc47956f_0
    - libxext-devel-cos6-x86_64 1.3.3 hf6a4bb0_0
    - libxrender-cos6-x86_64 0.9.10 h41db5cd_0
    - libxrender-devel-cos6-x86_64 0.9.10 ha8151bf_0
    - m4 1.4.18 h4e445db_0
    - make 4.2.1 h1bed415_1
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1j h27cfd23_0
    - perl 5.26.2 h14c3975_0
    - pkg-config 0.29.2 h1bed415_8
    - pthread-stubs 0.3 h0ce48e5_1
    - python 3.8.8 hdb3f193_4
    - readline 8.1 h27cfd23_0
    - sqlite 3.33.0 h62c20be_0
    - tk 8.6.10 hbc83047_0
    - xcb-proto 1.14 py38h7b6447c_0
    - xorg-x11-proto-devel-cos6-x86_64 7.7 h8d4a98b_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  host:
    - _libgcc_mutex 0.1 main
    - fontconfig 2.13.1 h6c09931_0
    - freetype 2.10.4 h5ab3b9f_0
    - glib 2.67.4 h36276a3_1
    - icu 58.2 he6710b0_3
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.1.0 hdf63c60_0
    - libpng 1.6.37 hbc83047_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - libuuid 1.0.3 h1bed415_2
    - libxcb 1.14 h7b6447c_0
    - libxml2 2.9.10 hb55368b_3
    - pcre 8.44 he6710b0_0
    - pixman 0.40.0 h7b6447c_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - fontconfig >=2.13.1,<3.0a0
    - freetype >=2.10.4,<3.0a0
    - glib >=2.67.4,<3.0a0
    - libgcc-ng >=7.3.0
    - libpng >=1.6.37,<1.7.0a0
    - libstdcxx-ng >=7.3.0
    - libxcb >=1.14,<2.0a0
    - pixman >=0.40.0,<1.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - cairo-trace --help
    - test -f $PREFIX/lib/libcairo.a
    - test -f $PREFIX/lib/libcairo.so
    - test -f $PREFIX/lib/libcairo-gobject.a
    - test -f $PREFIX/lib/libcairo-gobject.so
    - test -f $PREFIX/lib/libcairo-script-interpreter.a
    - test -f $PREFIX/lib/libcairo-script-interpreter.so
    - test -f $PREFIX/lib/pkgconfig/cairo-xlib.pc
    - test -f $PREFIX/include/cairo/cairo.h
    - grep -q "CAIRO_HAS_FC_FONT 1" $PREFIX/include/cairo/cairo-features.h
about:
  description: 'Cairo is a 2D graphics library with support for multiple output devices.

    It is designed to produce consistent output on all output media while

    taking advantage of display hardware acceleration when available.

    '
  dev_url: https://cgit.freedesktop.org/cairo/
  doc_source_url: https://cgit.freedesktop.org/cairo/tree/doc
  doc_url: http://cairographics.org/documentation/
  home: http://cairographics.org/
  license: LGPL 2.1 or MPL 1.1
  license_file: COPYING
  summary: Cairo is a 2D graphics library with support for multiple output devices.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - ocefpaf
    - pkgw
