# This file created by conda-build 3.21.5
# meta.yaml template originally from:
# /feedstock/recipe, last modified Thu Jan  6 08:43:57 2022
# ------------------------------------------------

package:
  name: parso
  version: 0.8.3
source:
  fn: parso-0.8.3.tar.gz
  sha256: 8c07be290bb59f03588915921e29e8a50002acaf2cdc5fa0e0114f91709fafa0
  url: https://pypi.io/packages/source/p/parso/parso-0.8.3.tar.gz
build:
  noarch: python
  number: '0'
  script: /opt/conda/conda-bld/parso_1641458642106/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
    -m pip install . -vv
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.10.26 h06a4308_2
    - certifi 2021.10.8 py39h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - ncurses 6.3 h7f8727e_2
    - openssl 1.1.1l h7f8727e_0
    - pip 21.2.4 py39h06a4308_0
    - python 3.9.7 h12debd9_1
    - readline 8.1 h27cfd23_0
    - setuptools 58.0.4 py39h06a4308_0
    - sqlite 3.37.0 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - tzdata 2021e hda174b7_0
    - wheel 0.37.0 pyhd3eb1b0_1
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7f8727e_4
  run:
    - python >=3.6
test:
  commands:
    - pip check
  imports:
    - parso
    - parso.pgen2
    - parso.python
  requires:
    - pip
    - python <3.10
about:
  description: 'Parso is a Python parser that supports error recovery and round-trip
    parsing for different Python versions (in multiple Python versions).

    Parso is also able to list multiple syntax errors in your python file.

    '
  dev_url: https://github.com/davidhalter/parso
  doc_url: https://parso.readthedocs.io/en/latest/
  home: https://github.com/davidhalter/parso
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python Parser
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - iron0012
    - synapticarbors
