# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/ca-certificates-2022.4.26-on-linux_64, last modified Mon May  2 21:04:05 2022
# ------------------------------------------------

package:
  name: ca-certificates
  version: 2022.4.26
source:
  fn: cacert.pem
  sha256: 08df40e8f528ed283b0e480ba4bcdbfdd2fdcf695a7ada1668243072d80f8b6f
  url: https://curl.haxx.se/ca/cacert-2022-04-26.pem
build:
  number: '0'
  string: h06a4308_0
requirements:
  build: []
  run: []
test:
  commands:
    - pip check
  requires:
    - curl
    - pip
about:
  dev_url: https://github.com/curl/curl/blob/master/scripts/mk-ca-bundle.pl
  doc_url: https://github.com/curl/curl/blob/master/docs/SSLCERTS.md
  home: https://curl.se/docs/caextract.html
  license: MPL-2.0
  license_family: Other
  license_file: LICENSE.txt
  summary: Certificates for use with other packages.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
