# This file created by conda-build 3.21.5
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pixman-0.40.0-on-linux_64, last modified Mon Sep 27 02:47:25 2021
# ------------------------------------------------

package:
  name: pixman
  version: 0.40.0
source:
  patches: null
  sha256: 6d200dec3740d9ec4ec8d1180e25779c00bc749f94278c8b9021f5534db223fc
  url: http://cairographics.org/releases/pixman-0.40.0.tar.gz
build:
  number: '1'
  run_exports:
    - pixman >=0.40.0,<1.0a0
  string: h7f8727e_1
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - gcc_impl_linux-64 7.5.0 h7105cf2_17
    - gcc_linux-64 7.5.0 h8f34230_30
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libgcc-devel_linux-64 7.5.0 hbbeae57_17
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libtool 2.4.6 h7b6447c_1005
    - make 4.2.1 h1bed415_1
    - pkg-config 0.29.2 h1bed415_8
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
  run:
    - libgcc-ng >=7.5.0
test:
  commands:
    - test -f ${PREFIX}/lib/libpixman-1.a
about:
  description: 'Pixman is a low-level software library for pixel manipulation, providing

    features such as image compositing and trapezoid rasterization.

    '
  dev_url: https://cgit.freedesktop.org/pixman/
  home: http://www.pixman.org/
  license: MIT
  license_file: COPYING
  summary: A low-level software library for pixel manipulation.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - katietz
    - ocefpaf
