# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/numexpr-2.8.1-python_3.7-blas_impl_openblas-on-linux_64, last modified Fri Dec 24 14:02:43 2021
# ------------------------------------------------

package:
  name: numexpr
  version: 2.8.1
source:
  sha256: cd779aa44dd986c4ef10163519239602b027be06a527946656207acf1f58113b
  url: https://pypi.io/packages/source/n/numexpr/numexpr-2.8.1.tar.gz
build:
  number: '0'
  script:
    - /tmp/build/80754af9/numexpr_1640686084435/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
      -m pip install . --no-deps -vv
  string: py37hecfb737_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - gcc_impl_linux-64 7.5.0 h7105cf2_17
    - gcc_linux-64 7.5.0 h8f34230_30
    - gxx_impl_linux-64 7.5.0 h0a5bf11_17
    - gxx_linux-64 7.5.0 hffc177d_30
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libgcc-devel_linux-64 7.5.0 hbbeae57_17
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-devel_linux-64 7.5.0 hf0c5c8d_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - blas 1.0 openblas
    - ca-certificates 2021.10.26 h06a4308_2
    - certifi 2021.10.8 py37h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgfortran-ng 7.5.0 ha8ba4b0_17
    - libgfortran4 7.5.0 ha8ba4b0_17
    - libgomp 9.3.0 h5101ec6_17
    - libopenblas 0.3.3 h5a2b251_3
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - ncurses 6.3 h7f8727e_2
    - nomkl 3.0 0
    - numpy 1.16.6 py37h0a8e133_3
    - numpy-base 1.16.6 py37h41b4c56_3
    - openblas-devel 0.3.3 3
    - openssl 1.1.1l h7f8727e_0
    - pip 21.2.2 py37h06a4308_0
    - python 3.7.11 h12debd9_0
    - readline 8.1 h27cfd23_0
    - setuptools 58.0.4 py37h06a4308_0
    - sqlite 3.36.0 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - wheel 0.37.0 pyhd3eb1b0_1
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7f8727e_4
  run:
    - blas * openblas
    - libgcc-ng >=7.5.0
    - libopenblas >=0.3.3,<1.0a0
    - libstdcxx-ng >=7.5.0
    - numpy >=1.16.6,<2.0a0
    - packaging
    - python >=3.7,<3.8.0a0
test:
  commands:
    - pip check
  imports:
    - numexpr
    - numexpr.interpreter
  requires:
    - nomkl
    - pip
about:
  description: 'Numexpr is a fast numerical expression evaluator for NumPy. With it,

    expressions that operate on arrays (like "3*a+4*b") are accelerated and use

    less memory than doing the same calculation in Python.

    '
  dev_url: https://github.com/pydata/numexpr
  doc_url: https://github.com/pydata/numexpr/wiki/Numexpr-Users-Guide
  home: https://github.com/pydata/numexpr
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Fast numerical expression evaluator for NumPy.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - djkirkham
    - msarahan
    - ocefpaf
    - scopatz
