# This file created by conda-build 3.22.0
# ------------------------------------------------

package:
  name: python
  version: 3.8.16
source:
  - patches:
      - patches/0001-Fix-off-by-one-error-in-_winapi_WaitForMultipleObjec.patch
      - patches/0002-Add-Anaconda-Distribution-version-logic.patch
      - patches/0003-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
      - patches/0004-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - patches/0005-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
      - patches/0006-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
      - patches/0007-Support-cross-compiling-byte-code.patch
      - patches/0008-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
      - patches/0009-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
      - patches/0010-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - patches/0011-Win32-Do-not-download-externals.patch
      - patches/0012-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
      - patches/0013-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0014-Disable-new-dtags-in-unixccompiler.py.patch
      - patches/0015-Fix-cross-compilation-on-Debian-based-distros.patch
      - patches/0016-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - patches/0017-Unvendor-openssl.patch
      - patches/0018-Unvendor-sqlite3.patch
      - patches/0019-venv-Revert-a-change-from-https-github.com-python-cp.patch
      - patches/0020-Win-Add-back-the-DLLSuffix-used-to-find-the-openssl-.patch
      - patches/0021-Use-ranlib-from-env-if-env-variable-is-set.patch
      - patches/0022-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0023-Revert-part-of-https-bugs.python.org-issue33895-http.patch
      - patches/0024-cross-compile-darwin.patch.patch
      - patches/0032-ctypes-link-to-coreFoundation.patch
    sha256: d85dbb3774132473d8081dcb158f34a10ccad7a90b96c7e50ea4bb61f5ce4562
    url: https://www.python.org/ftp/python/3.8.16/Python-3.8.16.tar.xz
build:
  activate_in_script: true
  detect_binary_files_with_prefix: true
  ignore_run_exports:
    - bzip2
  missing_dso_whitelist:
    - $RPATH/libc.so.6
    - $RPATH/libcrypt.so.1
    - $RPATH/libdl.so.2
    - $RPATH/libm.so.6
    - $RPATH/libnsl.so.1
    - $RPATH/libpthread.so.0
    - $RPATH/librt.so.1
    - $RPATH/libutil.so.1
  no_link: null
  number: 3
  run_exports:
    noarch:
      - python
  string: h7a1cb2a_3
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - gxx_impl_linux-64 11.2.0 h1234567_1
    - gxx_linux-64 11.2.0 hc2dff05_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.38 h1181459_1
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-devel_linux-64 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libtool 2.4.6 h6a678d5_1009
    - libuuid-cos6-x86_64 2.17.2 4
    - libuuid-devel-cos6-x86_64 2.17.2 4
    - libx11-common-cos6-x86_64 1.6.4 4
    - libx11-cos6-x86_64 1.6.4 4
    - libx11-devel-cos6-x86_64 1.6.4 4
    - make 4.2.1 h1bed415_1
    - pkg-config 0.29.2 h1bed415_8
    - sysroot_linux-64 2.17 h57e8cba_10
    - xorg-x11-proto-devel-cos6-x86_64 7.7 4
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2023.01.10 h06a4308_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.2 h6a678d5_6
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - ncurses 6.4 h6a678d5_0
    - openssl 1.1.1t h7f8727e_0
    - readline 8.0 h7b6447c_0
    - sqlite 3.40.1 h5082296_0
    - tk 8.6.12 h1ccaba5_0
    - xz 5.2.10 h5eee18b_1
    - zlib 1.2.13 h5eee18b_0
  run:
    - ld_impl_linux-64
    - libffi >=3.4,<3.5
    - libffi >=3.4,<4.0a0
    - libgcc-ng >=11.2.0
    - libstdcxx-ng >=11.2.0
    - ncurses >=6.4,<7.0a0
    - openssl >=1.1.1t,<1.1.2a
    - readline >=8.0,<9.0a0
    - sqlite >=3.40.1,<4.0a0
    - tk >=8.6.12,<8.7.0a0
    - xz >=5.2.10,<6.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - python -V
    - python3 -V
    - 2to3 -h
    - pydoc -h
    - python3-config --help
    - python -m venv test-venv
    - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    - _CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
      python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    - for f in ${CONDA_PREFIX}/lib/python*/_sysconfig*.py; do echo "Checking $f:";
      if [[ `rg @ $f` ]]; then echo "FAILED ON $f"; cat $f; exit 1; fi; done
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.a
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.nolto.a
    - pushd tests
    - pushd distutils
    - python setup.py install -v -v
    - python -c "import foobar"
    - popd
    - pushd distutils.cext
    - python setup.py install -v -v
    - python -c "import greet; greet.greet('Python user')" | rg "Hello Python"
    - popd
    - pushd prefix-replacement
    - bash build-and-test.sh
    - popd
    - pushd cmake
    - cmake -GNinja -DPY_VER=3.8.16
    - popd
    - popd
  files:
    - tests/cmake/*
    - tests/cython/*
    - tests/distutils.cext/*
    - tests/distutils/*
    - tests/prefix-replacement/*
  requires:
    - cmake
    - cython
    - gcc_linux-64 11.2.0.*
    - gxx_linux-64 11.2.0.*
    - ninja
    - ripgrep
    - setuptools
about:
  description: 'Python is a widely used high-level, general-purpose, interpreted,
    dynamic

    programming language. Its design philosophy emphasizes code

    readability, and its syntax allows programmers to express concepts in

    fewer lines of code than would be possible in languages such as C++ or

    Java. The language provides constructs intended to enable clear programs

    on both a small and large scale.

    '
  dev_url: https://devguide.python.org/
  doc_url: https://www.python.org/doc/versions/
  home: https://www.python.org/
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  license_url: https://docs.python.org/3.8/license.html
  summary: General purpose programming language
extra:
  copy_test_source_files: true
  feedstock-name: python
  final: true
  flow_run_id: 4dd8c51f-6ec1-43f1-8d6d-bdf16ea1e6a5
  recipe-maintainers:
    - isuruf
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/python-feedstock.git
  sha: 9f9c2650c1d8756cfaa025f2ce666b126ebd6646
