# This file created by conda-build 3.18.11
# ------------------------------------------------

package:
    name: numpy-base
    version: 1.16.6
source:
    -   patches:
            - 0001-fix-windows-case-sensitivity.patch
            - 0002-simplify-arch-flags.patch
            - 0003-Obtain-and-prefer-custom-gfortran-from-env-variable.patch
            - 0004-disable-memmap-filename-test-due-to-CI-link-confusio.patch
            - 0005-disable-broken-tests.patch
            - 0006-use-mklfft-when-available.patch
            - 0007-define-mkl_version-in-__init__.py.patch
            - 0008-intel-umath-optimizations.patch
            - 0009-intel-mkl_mem-all.patch
            - 0010-intel-init_mkl.patch
            - 0011-intel-mkl_random.patch
            - 0012-Remove-ICC-specific-flags.patch
            - 0013-Remove-np.invsqrt.patch
            - 0014-Rewrite-inlining.patch
            - 0015-Fixes-from-Intel-Distribution.patch
            - 0016-define-__THRESHOLD.patch
            - 0017-mark-known-failing-tests-on-ppc64le.patch
            - 0018-filter-out-warnings-when-importing-mkl_fft.patch
        sha256: e5cf3fdf13401885e8eea8170624ec96225e2174eb0c611c6f26dd33b489e3ff
        url: https://pypi.io/packages/source/n/numpy/numpy-1.16.6.zip
    -   folder: mkl_random
        sha256: 2270ef2834f6552850533aad01500d27c8e056f2cfbdbdb751593000aea1159e
        url: https://github.com/IntelPython/mkl_random/archive/v1.0.2.tar.gz
    -   folder: mkl_fft
        sha256: 3c7ed29e203c5b664ecafb11d767d62f9cae4aa56f9a95737e121192a66673bf
        url: https://github.com/IntelPython/mkl_fft/archive/v1.0.6.tar.gz
build:
    force_use_keys:
        - python
    noarch: false
    number: '0'
    script: install_base.sh
    string: py27hde5b4d6_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gfortran_impl_linux-64 7.3.0 hdf63c60_1
        - gfortran_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 mkl
        - ca-certificates 2020.1.1 0
        - certifi 2019.11.28 py27_0
        - cython 0.29.14 py27he6710b0_0
        - intel-openmp 2019.4 243
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - mkl 2019.4 243
        - mkl-devel 2019.4 243
        - mkl-include 2019.4 243
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - python 2.7.17 h9bab390_0
        - readline 7.0 h7b6447c_5
        - setuptools 44.0.0 py27_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - blas 1.0 mkl
        - libgcc-ng >=7.3.0
        - libgfortran-ng >=7,<8.0a0
        - mkl >=2019.4,<2020.0a0
        - mkl-service >=2,<3.0a0
        - python >=2.7,<2.8.0a0
test:
    commands:
        - test -e $SP_DIR/numpy/distutils/site.cfg
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
        - pelson
        - rgommers
