# This file created by conda-build 3.18.10
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/mkl_fft-1.0.15-python_2.7-on-linux_64, last modified Wed Nov  6 21:52:24 2019
# ------------------------------------------------

package:
    name: mkl_fft
    version: 1.0.15
source:
    sha256: 985f9e57d05324b07896ac7481779226cb9f234968b3595244f354fc90aa56c6
    url: https://github.com/IntelPython/mkl_fft/archive/v1.0.15.tar.gz
build:
    number: '0'
    script: /tmp/build/80754af9/mkl_fft_1573077333120/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        setup.py build install --single-version-externally-managed --record=record.txt
    string: py27ha843d7b_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_8
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 mkl
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py27_0
        - cython 0.29.13 py27he6710b0_0
        - intel-openmp 2019.4 243
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - mkl 2019.4 243
        - mkl-devel 2019.4 243
        - mkl-include 2019.4 243
        - ncurses 6.1 he6710b0_1
        - numpy-base 1.11.3 py27hde5b4d6_12
        - numpy-devel 1.11.3 py27h4ba5984_12
        - openssl 1.1.1d h7b6447c_3
        - python 2.7.17 h9bab390_0
        - readline 7.0 h7b6447c_5
        - setuptools 41.6.0 py27_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - blas 1.0 mkl
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - mkl >=2019.4,<2020.0a0
        - mkl-service >=2,<3.0a0
        - numpy >=1.11.3,<2.0a0
        - python >=2.7,<2.8.0a0
test:
    commands:
        - nosetests -v mkl_fft
    imports:
        - mkl_fft
        - mkl_fft._numpy_fft
        - mkl_fft._scipy_fft
    requires:
        - nose
about:
    description: NumPy-based implementation of Fast Fourier Transform using Intel
        (R) Math Kernel Library. Supports in-place and out-of-place, 1D and ND complex
        FFT on arrays of single and double precision with arbitrary memory layout,
        so long as array strides are multiples of its itemsize.
    home: http://github.com/IntelPython/mkl_fft
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: NumPy-based implementation of Fast Fourier Transform using Intel (R)
        Math Kernel Library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - oleksandr-pavlyk
