# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/mkl_random-1.1.0-python_2.7-on-linux_canary, last modified Tue Sep 24 18:19:21 2019
# ------------------------------------------------

package:
    name: mkl_random
    version: 1.1.0
source:
    sha256: 99c98de7cf543482a978b1c3a5bc88fb63caa7162d60b026d244ab459e16f599
    url: https://github.com/IntelPython/mkl_random/archive/v1.1.0.tar.gz
build:
    ignore_run_exports:
        - blas
        - libgcc-ng
    number: '0'
    script: /tmp/build/80754af9/mkl_random_1569349257889/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . --no-deps -vv
    string: py27hd6b4f25_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_8
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 mkl
        - ca-certificates 2019.8.28 0
        - certifi 2019.9.11 py27_0
        - cython 0.29.13 py27he6710b0_0
        - intel-openmp 2019.4 243
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - mkl 2019.4 243
        - mkl-devel 2019.4 243
        - mkl-include 2019.4 243
        - mkl-service 2.3.0 py27he904b0f_0
        - ncurses 6.1 he6710b0_1
        - numpy-base 1.14.6 py27hde5b4d6_5
        - numpy-devel 1.14.6 py27h4ba5984_5
        - openssl 1.1.1d h7b6447c_1
        - pip 19.2.3 py27_0
        - python 2.7.16 h9bab390_6
        - readline 7.0 h7b6447c_5
        - setuptools 41.2.0 py27_0
        - six 1.12.0 py27_0
        - sqlite 3.29.0 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.6 py27_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - mkl >=2019.4,<2020.0a0
        - mkl-service >=2,<3.0a0
        - numpy >=1.14.6,<2.0a0
        - python >=2.7,<2.8.0a0
test:
    commands:
        - nosetests -v mkl_random
    imports:
        - mkl_random
        - mkl_random.mklrand
    requires:
        - nose
        - numpy-base >=1.14
about:
    description: NumPy-based implementation of random number generation sampling using
        Intel (R) Math Kernel Library, mirroring numpy.random, but exposing all choices
        of sampling algorithms available in MKL.
    home: http://github.com/IntelPython/mkl_random
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Intel (R) MKL-powered package for sampling from common probability distributions
        into NumPy arrays.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - oleksandr-pavlyk
