# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /builder/conda/pytorch-nightly, last modified Mon Dec  7 19:42:50 2020
# ------------------------------------------------

package:
    name: pytorch
    version: 1.7.1
source:
    path: /pytorch
build:
    detect_binary_files_with_prefix: false
    features: null
    number: '0'
    script_env:
        - CMAKE_ARGS
        - CONDA_CUDATOOLKIT_CONSTRAINT
        - CUDA_VERSION
        - CUDNN_VERSION
        - DEBUG
        - DEVELOPER_DIR
        - EXTRA_CAFFE2_CMAKE_FLAGS
        - USE_CUDA
        - USE_DISTRIBUTED
        - USE_FBGEMM
    string: py3.8_cuda11.0.221_cudnn8.0.5_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - bzip2 1.0.8 h7b6447c_0
        - ca-certificates 2020.10.14 0
        - cmake 3.18.2 ha30ef3c_0
        - expat 2.2.10 he6710b0_2
        - krb5 1.18.2 h173b8e3_0
        - libcurl 7.71.1 h20c2e04_1
        - libedit 3.1.20191231 h14c3975_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libssh2 1.9.0 h1ba5d50_1
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libuv 1.40.0 h7b6447c_0
        - lz4-c 1.9.2 heb0550a_3
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - rhash 1.4.0 h1ba5d50_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
        - zstd 1.4.5 h9ceee32_0
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 mkl
        - ca-certificates 2020.10.14 0
        - certifi 2020.12.5 py38h06a4308_0
        - intel-openmp 2020.2 254
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libuv 1.40.0 h7b6447c_0
        - magma-cuda110 2.5.2 1
        - mkl 2020.2 256
        - mkl-include 2020.2 256
        - mkl-service 2.3.0 py38he904b0f_0
        - mkl_fft 1.2.0 py38h23d657b_0
        - mkl_random 1.1.1 py38h0573a6f_0
        - ncurses 6.2 he6710b0_1
        - ninja 1.10.2 py38hff7bd54_0
        - numpy 1.19.2 py38h54aff64_0
        - numpy-base 1.19.2 py38hfa32c7d_0
        - openssl 1.1.1h h7b6447c_0
        - pip 20.3 py38h06a4308_0
        - pkg-config 0.29.2 h1bed415_8
        - python 3.8.5 h7579374_1
        - pyyaml 5.3.1 py38h7b6447c_1
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.2 py38h06a4308_2
        - six 1.15.0 py38h06a4308_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - typing_extensions 3.7.4.3 py_0
        - wheel 0.36.0 pyhd3eb1b0_0
        - xz 5.2.5 h7b6447c_0
        - yaml 0.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - blas * mkl
        - cudatoolkit >=11.0,<11.1
        - libuv >=1.40.0,<2.0a0
        - mkl >=2018
        - ninja
        - numpy >=1.11
        - python >=3.8,<3.9.0a0
        - typing_extensions
test:
    commands:
        - OMP_NUM_THREADS=4 python ./test/run_test.py || true
    imports:
        - torch
    source_files:
        - test
about:
    home: http://pytorch.org/
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: PyTorch is an optimized tensor library for deep learning using GPUs and
        CPUs.
extra:
    copy_test_source_files: true
    final: true
