# This file created by conda-build 3.21.5
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/mkl_fft-1.3.1-python_3.7-on-linux_64, last modified Mon Oct 18 14:06:46 2021
# ------------------------------------------------

package:
  name: mkl_fft
  version: 1.3.1
source:
  sha256: 9039d301deb4c381b961a4c9cc889aa0e7e1dba04d1685c988ef36b2e2a66067
  url: https://github.com/IntelPython/mkl_fft/archive/v1.3.1.tar.gz
build:
  number: '0'
  script: /tmp/build/80754af9/mkl_fft_1634555083881/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    setup.py build install --single-version-externally-managed --record=record.txt
  string: py37hd3c417c_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - gcc_impl_linux-64 7.5.0 h7105cf2_17
    - gcc_linux-64 7.5.0 h8f34230_30
    - gxx_impl_linux-64 7.5.0 h0a5bf11_17
    - gxx_linux-64 7.5.0 hffc177d_30
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libgcc-devel_linux-64 7.5.0 hbbeae57_17
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-devel_linux-64 7.5.0 hf0c5c8d_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - blas 1.0 mkl
    - ca-certificates 2021.9.30 h06a4308_1
    - certifi 2021.10.8 py37h06a4308_0
    - cython 0.29.24 py37h295c915_0
    - intel-openmp 2021.3.0 h06a4308_3350
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgfortran-ng 7.5.0 ha8ba4b0_17
    - libgfortran4 7.5.0 ha8ba4b0_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - mkl 2021.3.0 h06a4308_520
    - mkl-devel 2021.3.0 h66538d2_520
    - mkl-include 2021.3.0 h06a4308_520
    - mkl-service 2.4.0 py37h7f8727e_0
    - ncurses 6.2 he6710b0_1
    - numpy-base 1.16.6 py37hdc34a94_3
    - openssl 1.1.1l h7f8727e_0
    - python 3.7.11 h12debd9_0
    - readline 8.1 h27cfd23_0
    - setuptools 58.0.4 py37h06a4308_0
    - six 1.16.0 pyhd3eb1b0_0
    - sqlite 3.36.0 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - blas 1.0 mkl
    - libgcc-ng >=7.5.0
    - libstdcxx-ng >=7.5.0
    - mkl >=2021.3.0,<2022.0a0
    - mkl-service >=2.3.0,<3.0a0
    - numpy >=1.16,<2.0a0
    - python >=3.7,<3.8.0a0
test:
  commands:
    - nosetests -v mkl_fft
  imports:
    - mkl_fft
    - mkl_fft._numpy_fft
    - mkl_fft._scipy_fft
  requires:
    - nose
about:
  description: NumPy-based implementation of Fast Fourier Transform using Intel (R)
    Math Kernel Library. Supports in-place and out-of-place, 1D and ND complex FFT
    on arrays of single and double precision with arbitrary memory layout, so long
    as array strides are multiples of its itemsize.
  home: http://github.com/IntelPython/mkl_fft
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: NumPy-based implementation of Fast Fourier Transform using Intel (R) Math
    Kernel Library.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - oleksandr-pavlyk
