# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Tue Jun  8 11:17:16 2021
# ------------------------------------------------

package:
  name: nettle
  version: 3.7.3
source:
  fn: nettle-3.7.3.tar.gz
  sha256: 661f5eb03f048a3b924c3a8ad2515d4068e40f67e774e8a26827658007e3bcf0
  url: https://ftp.gnu.org/gnu/nettle/nettle-3.7.3.tar.gz
build:
  number: '1'
  run_exports:
    - nettle >=3.7.3,<3.8.0a0
  string: hbbd107a_1
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - autoconf 2.69 pl526hebd4dad_5
    - binutils_impl_linux-64 2.33.1 he6710b0_7
    - binutils_linux-64 2.33.1 h9595d00_15
    - gcc_impl_linux-64 7.3.0 habb00fd_1
    - gcc_linux-64 7.3.0 h553295d_15
    - ld_impl_linux-64 2.33.1 h53a641e_7
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - m4 1.4.18 h4e445db_0
    - make 4.2.1 h1bed415_1
    - perl 5.26.2 h14c3975_0
  host:
    - _libgcc_mutex 0.1 main
    - gmp 6.1.2 h6c8ec71_1
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
  run:
    - gmp >=6.1.2
    - libgcc-ng >=7.3.0
test:
  commands:
    - test -f ${PREFIX}/lib/libnettle${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libhogweed${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libnettle.a
    - test ! -f ${PREFIX}/lib/libhogweed.a
about:
  description: Nettle is a low-level cryptographic library that is designed to fit
    easily in more or less any context. In crypto toolkits for object-oriented languages
    (C++, Python, Pike, ...), in applications like LSH or GNUPG, or even in kernel
    space. Simple, fast, extensible JSON encoder/decoder for Python
  dev_url: https://git.lysator.liu.se/nettle/nettle
  doc_url: https://www.lysator.liu.se/~nisse/nettle/nettle.html
  home: https://www.lysator.liu.se/~nisse/nettle/
  license: GPL-2.0-or-later AND LGPL-3.0-or-later
  license_family: GPL
  license_file: /tmp/build/80754af9/combined_recipe/LICENSE
  summary: Nettle is a low-level cryptographic library that is designed to fit easily
    in more or less any context
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - mingwandroid
    - sachalau
