# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libtiff-4.1.0-on-linux_64, last modified Mon Jun  1 19:09:55 2020
# ------------------------------------------------

package:
    name: libtiff
    version: 4.1.0
source:
    patches:
        - patches/0001-CVE-2017-11613_part1.patch
        - patches/0002-CVE-2017-11613_part2.patch
        - patches/fix_TIFFReadRawStrip_man_page_typo.patch
    sha256: 5d29f32517dadb6dbcd1255ea5bbc93a2b54b94fbf83653b4d65c7d6775b8634
    url: https://download.osgeo.org/libtiff/tiff-4.1.0.tar.gz
build:
    missing_dso_whitelist:
        - /opt/X11/lib/libGL.1.dylib
        - /opt/X11/lib/libglut.3.dylib
    number: '1'
    run_exports:
        - libtiff >=4.1.0,<5.0a0
    string: h2733197_1
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - make 4.2.1 h1bed415_1
    host:
        - _libgcc_mutex 0.1 main
        - jpeg 9b h024ee3a_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - lz4-c 1.9.2 he6710b0_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
        - zstd 1.4.4 h0b5b093_3
    run:
        - jpeg >=9b,<10a
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - xz >=5.2.5,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zstd >=1.4
        - zstd >=1.4.4,<1.4.5.0a0
test:
    commands:
        - test -f ${PREFIX}/lib/libtiff.a
        - test -f ${PREFIX}/lib/libtiffxx.a
        - test -f ${PREFIX}/lib/libtiff${SHLIB_EXT}
        - test -f ${PREFIX}/lib/libtiffxx${SHLIB_EXT}
about:
    description: 'This software provides support for the Tag Image File Format (TIFF),
        a

        widely used format for storing image data.

        '
    doc_url: http://www.libtiff.org/document.html
    home: http://www.libtiff.org/
    license: HPND
    license_file: COPYRIGHT
    summary: Support for the Tag Image File Format (TIFF).
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - msarahan
        - ocefpaf
        - stuarteberg
