# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed May 11 02:15:46 2022
# ------------------------------------------------

package:
  name: pyparsing
  version: 3.0.9
source:
  sha256: 2b020ecf7d21b687f219b71ecad3631f644a47f01403fa1d1036b0c6416d70fb
  url: https://pypi.io/packages/source/p/pyparsing/pyparsing-3.0.9.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/pyparsing_1652235407899/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2021.10.8 ha878542_0
    - flit-core 3.7.1 pyhd8ed1ab_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 11.2.0 h1d223b6_16
    - libgomp 11.2.0 h1d223b6_16
    - libnsl 2.0.0 h7f98852_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.11 h166bdaf_1014
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.3 h166bdaf_0
    - pip 22.0.4 pyhd8ed1ab_0
    - python 3.10.4 h2660328_0_cpython
    - python_abi 3.10 2_cp310
    - readline 8.1 h46c0cb4_0
    - setuptools 62.2.0 py310hff52083_0
    - sqlite 3.38.5 h4ff8645_0
    - tk 8.6.12 h27826a3_0
    - tzdata 2022a h191b570_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h166bdaf_1014
  run:
    - python >=3.6
test:
  commands:
    - pip check
  imports:
    - pyparsing
  requires:
    - pip
about:
  description: 'The pyparsing module is an alternative approach to creating and executing

    simple grammars, vs. the traditional lex/yacc approach, or the use of

    regular expressions. The pyparsing module provides a library of classes

    that client code uses to construct the grammar directly in Python code.

    '
  dev_url: https://svn.code.sf.net/p/pyparsing/code/
  doc_url: http://pyparsing.wikispaces.com/Documentation
  home: http://pyparsing.wikispaces.com/
  license: MIT
  license_file: LICENSE
  summary: Create and execute simple grammars
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jan-janssen
    - msarahan
    - ocefpaf
