# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pexpect-4.8.0-on-linux_64, last modified Mon Nov 16 21:45:37 2020
# ------------------------------------------------

package:
    name: pexpect
    version: 4.8.0
source:
    sha256: fc65a43959d153d0114afe13997d439c22823a27cefceb5ff35c2178c6784c0c
    url: https://pypi.io/packages/source/p/pexpect/pexpect-4.8.0.tar.gz
build:
    noarch: python
    number: '3'
    script: /tmp/build/80754af9/pexpect_1605563209008/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . -vv
    string: pyhd3eb1b0_3
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.10.14 0
        - certifi 2020.6.20 pyhd3eb1b0_3
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.4 py36h06a4308_0
        - python 3.6.12 hcff3b4d_2
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.1 py36h06a4308_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 pyhd3eb1b0_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - ptyprocess >=0.5
        - python
test:
    imports:
        - pexpect
about:
    description: 'Pexpect is a pure Python module for spawning child applications;

        controlling them; and responding to expected patterns in their output.

        '
    dev_url: https://github.com/pexpect/pexpect
    doc_source_url: https://github.com/pexpect/pexpect/blob/master/doc/index.rst
    doc_url: http://pexpect.readthedocs.org/
    home: http://pexpect.sourceforge.net/
    license: ISC
    license_family: Other
    license_file: LICENSE
    summary: Pexpect makes Python a better tool for controlling other applications.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jquast
        - ocefpaf
        - pelson
        - takluyver
