# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pandas-1.3.5-python_3.7-on-linux_64, last modified Thu Jan  6 09:05:41 2022
# ------------------------------------------------

package:
  name: pandas
  version: 1.3.5
source:
  patches: null
  sha256: 1e4285f5de1012de20ca46b188ccf33521bff61ba5c5ebd78b4fb28e5416a9f1
  url: https://github.com/pandas-dev/pandas/releases/download/v1.3.5/pandas-1.3.5.tar.gz
build:
  entry_points:
    - matplotlib = pandas:plotting._matplotlib
  number: '0'
  script:
    - /tmp/build/80754af9/pandas_1641461141313/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
      -m pip install -vv --no-deps --ignore-installed . --global-option="build_ext"
      --global-option="-j${CPU_COUNT}" --no-use-pep517
  string: py37h8c16a72_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - gcc_impl_linux-64 7.5.0 h7105cf2_17
    - gcc_linux-64 7.5.0 h8f34230_30
    - gxx_impl_linux-64 7.5.0 h0a5bf11_17
    - gxx_linux-64 7.5.0 hffc177d_30
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libgcc-devel_linux-64 7.5.0 hbbeae57_17
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-devel_linux-64 7.5.0 hf0c5c8d_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - patch 2.7.6 h7b6447c_1001
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - blas 1.0 mkl
    - ca-certificates 2021.10.26 h06a4308_2
    - certifi 2021.10.8 py37h06a4308_0
    - cython 0.29.25 py37hdbfa776_0
    - intel-openmp 2021.4.0 h06a4308_3561
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - mkl 2019.4 243
    - mkl-service 2.3.0 py37he8ac12f_0
    - mkl_fft 1.0.14 py37hd81dba3_0
    - mkl_random 1.0.4 py37hd81dba3_0
    - ncurses 6.3 h7f8727e_2
    - numpy 1.19.2 py37h54aff64_0
    - numpy-base 1.19.2 py37hfa32c7d_0
    - openssl 1.1.1l h7f8727e_0
    - pip 21.2.2 py37h06a4308_0
    - python 3.7.11 h12debd9_0
    - readline 8.1 h27cfd23_0
    - setuptools 58.0.4 py37h06a4308_0
    - six 1.16.0 pyhd3eb1b0_0
    - sqlite 3.37.0 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - wheel 0.37.0 pyhd3eb1b0_1
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7f8727e_4
  run:
    - bottleneck >=1.2.1
    - libgcc-ng >=7.5.0
    - libstdcxx-ng >=7.5.0
    - numexpr >=2.7.0
    - numpy >=1.19.2,<2.0a0
    - python >=3.7,<3.8.0a0
    - python-dateutil >=2.7.3
    - pytz >=2017.3
test:
  commands:
    - pip check
  imports:
    - pandas
  requires:
    - hypothesis >=3.58
    - pip
    - pytest >=6.0
    - pytest-xdist
about:
  dev_url: https://github.com/pandas-dev/pandas
  doc_url: https://pandas.pydata.org/pandas-docs/stable/
  home: http://pandas.pydata.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: High-performance, easy-to-use data structures and data analysis tools.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - TomAugspurger
    - WillAyd
    - jorisvandenbossche
    - jreback
    - msarahan
    - ocefpaf
    - simonjayhawkins
