# This file created by conda-build 3.21.4
# ------------------------------------------------

package:
  name: libgfortran4
  version: 7.5.0
source:
  path: /home/builder/ktietz/cos6/ctng-compilers-feedstock/recipe
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  ignore_run_exports:
    - __glibc
  missing_dso_whitelist:
    - '*'
  number: 17
  string: ha8ba4b0_17
requirements:
  host:
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - sysroot_linux-64 2.17 h57e8cba_10
  run: []
  run_constrained:
    - libgfortran-ng 7.5.0 *_17
test:
  commands:
    - test -f ${PREFIX}/lib/libgfortran.so
about:
  home: https://gcc.gnu.org/
  license: GPL-3.0-only WITH GCC-exception-3.1
  summary: The GNU Fortran Runtime Library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - beckermr
    - isuruf
