# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libtiff-4.2.0-on-linux_64, last modified Tue Mar 23 09:34:27 2021
# ------------------------------------------------

package:
  name: libtiff
  version: 4.2.0
source:
  - folder: .
    patches:
      - patches/fix_TIFFReadRawStrip_man_page_typo.patch
      - use_unix_io.patch
    sha256: eb0484e568ead8fa23b513e9b0041df7e327f4ee2d22db5a533929dfc19633cb
    url: https://download.osgeo.org/libtiff/tiff-4.2.0.tar.gz
  - fn: hopper_lzw.tif
    sha256: 246e5de06ed6f4c63d8389fcb3342b18909e0f362a5a22f76f779ad52f46090d
    url: https://github.com/python-pillow/Pillow/raw/master/Tests/images/hopper_lzw.tif
build:
  missing_dso_whitelist:
    - /opt/X11/lib/libGL.1.dylib
    - /opt/X11/lib/libglut.3.dylib
  number: '0'
  run_exports:
    - libtiff >=4.2.0,<5.0a0
  string: h85742a9_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - binutils_impl_linux-64 2.33.1 he6710b0_7
    - binutils_linux-64 2.33.1 h9595d00_15
    - gcc_impl_linux-64 7.3.0 habb00fd_1
    - gcc_linux-64 7.3.0 h553295d_15
    - gxx_impl_linux-64 7.3.0 hdf63c60_1
    - gxx_linux-64 7.3.0 h553295d_15
    - ld_impl_linux-64 2.33.1 h53a641e_7
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - libtool 2.4.6 h7b6447c_1005
    - make 4.2.1 h1bed415_1
  host:
    - _libgcc_mutex 0.1 main
    - jpeg 9b h024ee3a_2
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - libwebp-base 1.2.0 h27cfd23_0
    - lz4-c 1.9.3 h2531618_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
    - zstd 1.4.5 h9ceee32_0
  run:
    - jpeg >=9b,<10a
    - libgcc-ng >=7.3.0
    - libstdcxx-ng >=7.3.0
    - libwebp-base
    - xz >=5.2.5,<6.0a0
    - zlib >=1.2.11,<1.3.0a0
    - zstd >=1.4.5,<1.4.6.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libtiff.a
    - test -f ${PREFIX}/lib/libtiffxx.a
    - test -f ${PREFIX}/lib/libtiff.so
    - test -f ${PREFIX}/lib/libtiffxx.so
    - python -m trace --trace --ignore-dir $CONDA_PREFIX downstream_tests.py
  files:
    - downstream_tests.py
  requires:
    - numpy
    - opencv
    - pillow
    - python 3.7.*
  source_files:
    - hopper_lzw.tif
about:
  description: 'This software provides support for the Tag Image File Format (TIFF),
    a

    widely used format for storing image data.

    '
  doc_url: http://www.libtiff.org/document.html
  home: http://www.libtiff.org/
  license: HPND
  license_file: COPYRIGHT
  summary: Support for the Tag Image File Format (TIFF).
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - stuarteberg
