boost_cpp: 1.68.0
c_compiler: gcc
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
docker_image: condaforge/linux-anvil-comp7
fortran_compiler: gfortran
ignore_build_only_deps: numpy
libprotobuf: '3.6'
lua: '5'
lz4_c: 1.8.1
numpy: '1.11'
perl: 5.26.0
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x.x
    max_pin: x.x.x
  boost-cpp:
    max_pin: x.x.x
  libprotobuf:
    max_pin: x.x
  lz4-c:
    max_pin: x.x.x
  snappy:
    max_pin: x.x.x
  zlib:
    max_pin: x.x
  zstd:
    max_pin: x.x.x
python: '3.7'
r_base: '3.5'
snappy: 1.1.7
target_platform: linux-64
zlib: '1.2'
zstd: 1.3.3
