# This file created by conda-build 3.18.9
# ------------------------------------------------

package:
    name: numpy
    version: 1.17.0
source:
    -   patches:
            - 0001-fix-windows-case-sensitivity.patch
            - 0002-simplify-arch-flags.patch
            - 0003-Obtain-and-prefer-custom-gfortran-from-env-variable.patch
            - 0004-disable-memmap-filename-test-due-to-CI-link-confusio.patch
            - 0005-disable-broken-tests.patch
            - 0017-mark-known-failing-tests-on-ppc64le.patch
            - 0018-osx-disable-lto-for-ld-test.patch
        sha256: 951fefe2fb73f84c620bec4e001e80a80ddaa1b84dce244ded7f1e0cbe0ed34a
        url: https://pypi.io/packages/source/n/numpy/numpy-1.17.0.zip
build:
    force_use_keys:
        - python
    noarch: false
    number: '0'
    string: py36h99e49ec_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - gfortran_impl_linux-64 7.3.0 hdf63c60_1
        - gfortran_linux-64 7.3.0 h553295d_8
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 openblas
        - ca-certificates 2019.5.15 1
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libopenblas 0.3.3 h5a2b251_3
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - nomkl 3.0 0
        - openblas-devel 0.3.3 3
        - openssl 1.1.1c h7b6447c_1
        - python 3.6.9 h265db76_0
        - readline 7.0 h7b6447c_5
        - sqlite 3.29.0 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - blas * openblas
        - libgcc-ng >=7.3.0
        - libgfortran-ng >=7,<8.0a0
        - libopenblas >=0.3.3,<1.0a0
        - numpy-base 1.17.0 py36h2f8d375_0
        - python >=3.6,<3.7.0a0
test:
    commands:
        - f2py -h
        - python -c "import numpy; numpy.show_config()"
    imports:
        - numpy
        - numpy.linalg.lapack_lite
    requires:
        - gcc_linux-64 7.3.0.*
        - gfortran_linux-64 7.3.0.*
        - nomkl
        - pytest
    script: numpy_test.py
about:
    description: 'NumPy is the fundamental package needed for scientific computing
        with Python.

        '
    dev_source_url: https://github.com/numpy/numpy/tree/master/doc
    dev_url: https://github.com/numpy/numpy
    doc_url: https://docs.scipy.org/doc/numpy-1.17.0/reference/
    home: http://numpy.scipy.org/
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Array processing for numbers, strings, records, and objects.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
        - pelson
        - rgommers
