# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/bottleneck-1.3.4-python_3.7-numpy_1.16-on-linux_64, last modified Wed Mar 23 09:45:46 2022
# ------------------------------------------------

package:
  name: bottleneck
  version: 1.3.4
source:
  sha256: 1764a7f4ad58c558723c542847eb367ab0bbb6d880a4e5d5eef30a0ece5cecea
  url: https://pypi.io/packages/source/b/bottleneck/Bottleneck-1.3.4.tar.gz
build:
  number: '0'
  script: /tmp/build/80754af9/bottleneck_1648028896657/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . -vv
  string: py37hce1f21e_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.35.1 h27ae35d_9
    - binutils_linux-64 2.35.1 h454624a_30
    - gcc_impl_linux-64 7.5.0 h7105cf2_17
    - gcc_linux-64 7.5.0 h8f34230_30
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libgcc-devel_linux-64 7.5.0 hbbeae57_17
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - blas 1.0 mkl
    - ca-certificates 2022.2.1 h06a4308_0
    - certifi 2021.10.8 py37h06a4308_2
    - intel-openmp 2021.4.0 h06a4308_3561
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgfortran-ng 7.5.0 ha8ba4b0_17
    - libgfortran4 7.5.0 ha8ba4b0_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - mkl 2021.4.0 h06a4308_640
    - mkl-service 2.4.0 py37h7f8727e_0
    - mkl_fft 1.3.1 py37hd3c417c_0
    - mkl_random 1.2.2 py37h51133e4_0
    - ncurses 6.3 h7f8727e_2
    - numpy 1.16.6 py37h2d18471_3
    - numpy-base 1.16.6 py37hdc34a94_3
    - openssl 1.1.1n h7f8727e_0
    - pip 21.2.2 py37h06a4308_0
    - python 3.7.11 h12debd9_0
    - readline 8.1.2 h7f8727e_1
    - setuptools 58.0.4 py37h06a4308_0
    - six 1.16.0 pyhd3eb1b0_1
    - sqlite 3.38.0 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7f8727e_4
  run:
    - libgcc-ng >=7.5.0
    - numpy >=1.16.6,<2.0a0
    - python >=3.7,<3.8.0a0
test:
  commands:
    - pip check
    - python -c "import bottleneck; bottleneck.test()"
  imports:
    - bottleneck
    - bottleneck.move
    - bottleneck.nonreduce
    - bottleneck.nonreduce_axis
    - bottleneck.reduce
    - bottleneck.slow
    - bottleneck.tests
  requires:
    - pip
    - pytest
about:
  description: 'Bottleneck is a collection of fast NumPy array functions written in

    Cython.

    '
  dev_url: https://github.com/pydata/bottleneck
  doc_url: https://bottleneck.readthedocs.io
  home: https://github.com/pydata/bottleneck
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Fast NumPy array functions written in Cython.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - msarahan
    - ocefpaf
    - qwhelan
    - wesm
