# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Wed Jan 25 17:12:05 2023
# ------------------------------------------------

package:
  name: giflib
  version: 5.2.1
source:
  - patches: null
    sha256: 31da5562f44c5f15d63340a09a4fd62b48c45620cd302f77a6d9acf0077879bd
    url: https://downloads.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz
build:
  number: '1'
  run_exports:
    - giflib >=5.2.1,<5.3.0a0
  string: h5eee18b_1
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - bzip2 1.0.8 h7b6447c_0
    - c-ares 1.18.1 h7f8727e_0
    - ca-certificates 2023.01.10 h06a4308_0
    - cmake 3.22.1 h1fce559_0
    - expat 2.4.9 h6a678d5_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - krb5 1.19.4 h568e23c_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libcurl 7.87.0 h91b91d3_0
    - libedit 3.1.20221030 h5eee18b_0
    - libev 4.33 h7f8727e_1
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libnghttp2 1.46.0 hce63b2e_0
    - libssh2 1.10.0 h8f2d780_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuv 1.40.0 h7b6447c_0
    - lz4-c 1.9.4 h6a678d5_0
    - make 4.2.1 h1bed415_1
    - ncurses 6.3 h5eee18b_3
    - openssl 1.1.1s h7f8727e_0
    - rhash 1.4.1 h3c74f83_1
    - sysroot_linux-64 2.17 h57e8cba_10
    - xz 5.2.10 h5eee18b_1
    - zlib 1.2.13 h5eee18b_0
    - zstd 1.5.2 ha4553b6_0
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
  run:
    - libgcc-ng >=11.2.0
test:
  commands:
    - gifbuild -h
    - giffix -h
    - giftext -h
    - gifclrmp -h
    - if gif2rgb -h; then exit 1; else exit 0; fi
about:
  home: https://giflib.sourceforge.net
  license: MIT
  license_file:
    - COPYING
  summary: Library for reading and writing gif images
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 61a1d336-d28c-4938-bd8a-3eb75921701e
  recipe-maintainers:
    - 183amir
    - isuruf
    - msarahan
    - ocefpaf
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/giflib-feedstock.git
  sha: 97837b1ba1b26bcb9b88fd8457e13dcdef576322
