# This file created by conda-build 3.10.9+36.gd10dbde.dirty
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/ffmpeg-feedstock/recipe, last modified Sun Jul  8 21:42:54 2018
# ------------------------------------------------

package:
    name: ffmpeg
    version: '4.0'
source:
    sha256: dc4b1c622baa34fc68d763cd2818e419d1af90271e0506604905f25a46ea8273
    url: https://ffmpeg.org/releases/ffmpeg-4.0.tar.gz
build:
    number: '0'
    run_exports:
        - ffmpeg >=4.0,<4.1.0a0
    string: hcdf2ecd_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 had2808c_27
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 h550dcbe_27
        - gxx_impl_linux-64 7.2.0 hdf63c60_3
        - gxx_linux-64 7.2.0 h550dcbe_27
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - libtool 2.4.6 h544aabb_3
        - make 4.2.1 h1bed415_1
        - pkg-config 0.29.2 h1bed415_8
        - yasm 1.3.0 h99c0ef8_2
    host:
        - bzip2 1.0.6 h14c3975_5
        - freetype 2.9.1 h8a8886c_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - libopus 1.2.1 hb9ed12e_0
        - libpng 1.6.34 hb9fc6fc_0
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - libvpx 1.7.0 h439df22_0
        - zlib 1.2.11 ha838bed_2
    run:
        - bzip2 >=1.0.6,<2.0a0
        - freetype >=2.9.1,<3.0a0
        - libgcc-ng >=7.2.0
        - libopus >=1.2.1,<2.0a0
        - libstdcxx-ng >=7.2.0
        - libvpx >=1.7.0,<1.8.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - ffmpeg --help
        - ffmpeg -codecs | grep "DEVI.S zlib"
        - test -f $PREFIX/lib/libavcodec.so
        - test -f $PREFIX/lib/libavdevice.so
        - test -f $PREFIX/lib/libswresample.so
        - test -f $PREFIX/lib/libpostproc.so
        - test -f $PREFIX/lib/libavfilter.so
        - test -f $PREFIX/lib/libswresample.so
        - test -f $PREFIX/lib/libavcodec.so
        - test -f $PREFIX/lib/libavformat.so
        - test -f $PREFIX/lib/libswscale.so
        - test -f $PREFIX/lib/libavresample.so
about:
    dev_url: https://ffmpeg.org/developer.html
    doc_url: https://ffmpeg.org/documentation.html
    home: http://www.ffmpeg.org/
    license: GPL 3
    license_file: COPYING.GPLv3
    summary: Cross-platform solution to record, convert and stream audio and video.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - 183amir
        - carlodri
        - caspervdw
        - danielballan
        - jakirkham
        - jjhelmus
        - mingwandroid
        - ocefpaf
        - patricksnape
        - sdvillal
